---
title: "Lecture 04: Distribution and Estimation"
subtitle: "Modern Method Modeling 2024"
author: "Jihong Zhang*, Ph.D; Jinbo He, Ph.D"
institute: | 
  Educational Statistics and Research Methods (ESRM) Program*
  
  University of Arkansas
date: "2024-09-16"
sidebar: false
execute: 
  echo: true
  warning: false
output-location: column
format: 
  html: 
    page-layout: full
    toc: true
    toc-depth: 2
    toc-expand: true
    lightbox: true
    code-fold: false
  uark-revealjs:
    scrollable: true
    chalkboard: true
    embed-resources: false
    code-fold: false
    number-sections: false
    footer: "ESRM 64503: Lecture 04: Distribution and Estimation"
    slide-number: c/t
    tbl-colwidths: auto
    output-file: slides-index.html
---

## Today's Class

-   [The building blocks]{style="color: tomato"}: **The basics of mathematical statistics:**

    -   Random variables: Definition & Types

    -   Univariate distribution

        -   General terminology (e.g., sufficient statistics)

        -   Univariate normal (aka Gaussian)

        -   Other widely used univariate distributions

    -   Types of distributions: Marginal \| Conditional \| Joint

    -   Expected values: means, variances, and the algebra of expectations

    -   Linear combinations of random variables

-   [The finished product]{style="color: violet"}: **How the GLM fits within statistics**

    -   The GLM with the normal distribution

    -   The statistical assumptions of the GLM

    -   How to assess these assumptions

# Unit 1: Random Variables & Statistical Distribution

## Definition of Random Variables

[**Random:**]{.underline} situations in which the certainty of the outcome is unkown and is at least in part due to chanvce

[**Variable:**]{.underline} a value that may change give the scope of a given problem or set of operations

[**Random Variable**]{.underline}: a variable whose outcome depends on chance (possible values might represent the possible outcomes of a yet-to-be performed experiment)

Today, we will denote a random variable with a lower-cased: ***x***

## Types of Random Variables

1.  **Continuous**
    -   Examples of continuous random variables:
        -   ***x*** represent the height of a person, draw at random
        -   *Y* (the outcome/DV in a GLM*)*
        -   Some variables like **exam score or motivation scores** are not "true" continuous variables, but it is convenient to consider them as "continuous"
2.  **Discrete** (also called categorical, generally)
    -   Example of discrete random variables:
        -   ***x*** represents the gender of a person, drawn at random
        -   *Y* (outcomes like yes/no; pass/not pass; master / not master a skill; survive / die)
3.  Mixture of Continuous and Discrete:
    -   Example of mixture:
\begin{equation}
  x =
    \begin{cases}
      RT & \text{between 0 and 45 seconds} \\
      0 & \text{otherwise}
    \end{cases}       
\end{equation}
