---
title: ""
listing:
  - id: posts
    contents: posts/**/*.[Rq]md
    type: grid
    fields: [image, date, reading-time, title]
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    page-size: 3
    feed: true
  - id: lectures
    contents: teaching/**/*_syllabus.[Rq]md
    fields: [image, date, title]
    sort: "date desc"
    type: grid
    max-items: 3
format: 
  html:
    code-tools: false
    comments: false
    toc: false
---



::: separator
[Experience]{.next-section}
:::

::: {.panel-tabset align="left"}
## Experience

-   University of Arkansas \| **Assistant Professor** \| [Jan 2024 - Current]{style="color:darkgrey;"}
-   The Chinese University of Hong Kong \| **Postdoctoral Fellow** \| [Dec 2022 - June 2023]{style="color:darkgrey;"}
-   Stanford Research Institute (SRI) \| **Associate Researcher (Intern)** \| [June 2021 - Jan 2022]{style="color:darkgrey;"}

<a href="./uploads/Curriculum_Vitae.pdf"><button type="button" class="btn btn-primary float-end btn-sm">See C.V.</button></a>

## Education

-   **Ph.D.** \| Educational Measurement & Statistics \| **University of Iowa** \| Jan [2019 - Dec 2022]{style="color:darkgrey;"}
-   **M.S.** \| Educational Psychology & Research \| **University of Kansas** \| Aug [2015 - Dec 2019]{style="color:darkgrey;"}
-   **B.S.** \| Applied Psychology \| **Soochow University** \| Aug [2009 - Dec 2013]{#date style="color:darkgrey;"}
-   **B.S.** \| Law \| **Soochow University** \| [2011 - 2013]{style="color:darkgrey;"}

## Interests

-   AI in Educational Measurement and Psychometrics
-   Bayesian Psychometric Modeling
-   Psychometric network and Latent variable modeling
-   Machine Learning and data mining in Education
-   Diagnostic Classification Models
:::

::: separator
[News]{.next-section}
:::


::: macwindow

-   2025-03-30: New journal paper accepted by [Behavioral Sciences]{.underline}: *Comparing Frequentist and Bayesian Methods for Factorial Invariance with Latent Distribution Heterogeneity*, Authors: Xinya Liang \*, Ji Li, Mauricio Garnier-Villarreal, Jihong Zhang

-   2025-03-27: New journal paper published (online first) by [Learning and Individual Differences]{.underline}:*Math anxiety is associated with skipping problems and less help-seeking behavior after error commission*, 

-   2025-02-28: I have been elected to serve as Secretary/Treasurer (3-year term begins in 2025) of the Cognition and Assessment SIG (SIG #167) of the American Educational Research Association (AERA). My term will begin at the conclusion of the 2025 AERA Annual Meeting.

:::




::: separator
[Teaching & Research]{.next-section}
:::

## Teaching

::: {#lectures}
:::

## Recent Posts

::: {#posts}
:::

<a href="./posts.qmd"><button type="button" class="btn btn-primary float-end btn-sm">See all</button></a>
