---
title: 'Blog | Jihong'
subtitle: ''
listing:
  - id: posts_2025
    template: assets/ejs/article-lists.ejs
    contents: "posts/2025/**/*.[Rq]md"
    sort: "date desc"
    categories: true
  - id: posts_2024
    template: assets/ejs/article-lists.ejs
    contents: "posts/2024/**/*.[Rq]md"
    sort: "date desc"
    categories: true
  - id: posts_2023
    template: assets/ejs/article-lists.ejs
    contents: "posts/2023/**/*.[Rq]md"
    sort: "date desc"
    categories: true  
  - id: posts_2022
    template: assets/ejs/article-lists.ejs
    contents: "posts/2022/**/*.[Rq]md"
    sort: "date desc"
    categories: true  
  - id: posts_2021
    template: assets/ejs/article-lists.ejs
    contents: "posts/2021/**/*.[Rq]md"
    sort: "date desc"
    categories: true    
  - id: posts_2019
    template: assets/ejs/article-lists.ejs
    contents: "posts/2019/**/*.[Rq]md"
    sort: "date desc"
    categories: true    
  - id: posts_2018
    template: assets/ejs/article-lists.ejs
    contents: "posts/2018/**/*.[Rq]md"
    sort: "date desc"
    categories: true    
  - id: posts_2017
    template: assets/ejs/article-lists.ejs
    contents: "posts/2017/**/*.[Rq]md"
    sort: "date desc"
    categories: true    
freeze: false    
toc-title: Year
toc-location: left
date-format: "MMM DD"
page-layout: full
execute: 
  warning: false
  message: false
format: 
  html:
    code-tools: false
    comments: false
---

```{r}
#| echo: false
#| fig-height: 4
library(plotly)
post_folders <- as.numeric(list.files("posts")[grepl(list.files("posts"), pattern = "20")])
post_folders <- sort(post_folders, decreasing = TRUE)
## Find the relative path
path_post <- paste0("posts/", post_folders)
## Check out how many posts in each folder by year
freq_post <- data.frame(
  year = post_folders,
  number_post = sapply(path_post, \(x) length(list.files(x)))
)

## font setting
t <- list(
  family = "Abel",
  size = 16,
  color = '#404041')
plot_ly(x =~year, y=~number_post, data = freq_post, 
        showlegend = FALSE) |> 
  add_lines(color=I("tan")) |> 
  add_bars(color = I("tan"), opacity = .3) |> 
  add_markers(color=I("tan")) |> 
  add_text(y=~number_post+.5, text=~number_post) |> 
  layout(
    paper_bgcolor = "#FAF9F6",
    plot_bgcolor='#FAF9F6',
    title = "",
    xaxis = list(title = "Number of Posts by Year"), 
    yaxis = list(title = ""),
    font = t)
```

```{r}
#| results: asis
#| echo: false
post_text <- glue::glue("## {post_folders}\n\n:::{{#posts_{post_folders}}}\n:::  \n\n")
post_text
```
