---
title: 'Teaching | Jihong Zhang'
subtitle: ''
listing:
  - id: lectures
    contents: /teaching/2025*/*_syllabus.[Rq]md
    sort: "date desc"
    type: grid
sidebar: id-history
format: 
  html:
    code-tools: false
    toc: false
    comments: false
    grid:
      sidebar-width: 400px
---

::: {#lectures}
:::

::: nice-paragraph
1.  **ESRM 64103. [Experimental Design in Education](teaching/2025-01-13-Experiment-Design/ESRM64103_syllabus.qmd)**. 3 Hours.
    -   Principles of experimental design as applied to educational situations. Special emphasis on analysis of variance techniques used in educational research. Prerequisite: [ESRM64003](https://catalog.uark.edu/search/?P=ESRM%2064003 "ESRM 64003") with a grade of C or better or an equivalent course with a grade of C or better. (Typically offered: **Spring**)
2.  **ESRM 6990V. [Advanced Seminar: Introduction to R](teaching/2025-01-13-Adv-Seminar-Intro-to-R/ESRM6990V_syllabus.qmd).** 3 Hours
    -   This seminar covers basics of R, data wrangling, data visualization, project version control via git etc. (Typically offered: **Spring**)
3.  **ESRM64503. [Applied Multivariate Statistics](teaching/2024-07-21-applied-multivariate-statistics-esrm64503/ESRM64503_syllabus.qmd).** 3 Hours.
    -   Multivariate statistical procedures as applied to educational research settings including discriminant analysis, principal components analysis, factor analysis, canonical correlation, and cluster analysis. Emphasis on use of existing computer statistical packages. Prerequisite: [ESRM64103](https://catalog.uark.edu/search/?P=ESRM%2064103 "ESRM 64103") and [ESRM64203](https://catalog.uark.edu/search/?P=ESRM%2064203 "ESRM 64203"), both with a grade of C or better. (Typically offered: **Spring**)
4.  **ESRM65503. [Advanced Multivariate Statistics](teaching/2024-01-12-syllabus-adv-multivariate-esrm-6553/ESRM6554_syllabus.qmd).** 3 Hours.
    -   Builds on the foundation provided in Multivariate and introduces techniques that extend methodological elements of canonical, discriminant, factor analytic, and longitudinal analyses, providing the mathematical and theoretical foundations necessary for these designs. Prerequisite: [ESRM64503](https://catalog.uark.edu/search/?P=ESRM%2064503 "ESRM 64503") with a grade of C or better. (Typically offered: **Spring Even Years**)
:::
