{
  "hash": "4de1b2f733ecf637332aca66ccdc21f2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 12: Principal Components Analysis and Factor Analysis\"\nsubtitle: \"Absolute Model fit and Model Interpretation\"\nauthor: \"Jihong Zhang*, Ph.D\"\ninstitute: | \n  Educational Statistics and Research Methods (ESRM) Program*\n  \n  University of Arkansas\ndate: \"2024-10-09\"\ndate-modified: \"2024-10-11\"\nsidebar: false\nexecute: \n  echo: true\n  warning: false\noutput-location: default\ncode-annotations: below\nhighlight-style: \"nord\"\nformat: \n  uark-revealjs:\n    scrollable: true\n    chalkboard: true\n    embed-resources: false\n    code-fold: false\n    number-sections: false\n    footer: \"ESRM 64503 - Lecture 12: Absolute Model fit and Path Analysis\"\n    slide-number: c/t\n    tbl-colwidths: auto\n    output-file: slides-index.html\n  html: \n    page-layout: full\n    toc: true\n    toc-depth: 2\n    toc-expand: true\n    lightbox: true\n    code-fold: false\n    fig-align: center\nfilters:\n  - quarto\n  - line-highlight\nbibliography: references.bib\n---\n\n\n\n\n## Course Evaluation\n\n## Today's Class\n\n-   Methods for exploratory factor analysis (EFA)\n    -   Principal Components-based\n    -   Maximum Likelihood-based Exploratory Factor Analysis\n    -   Exploratory Structural Equation Modeling\n-   Comparisons of CFA and EFA\n-   How to do exploratory analyses with CFA\n    -   Structure of no items known\n    -   Structure of some items known\n\n\n\n\n::: {.cell output-location='default'}\n\n```{.r .cell-code}\nlibrary(ESRM64503)\nlibrary(kableExtra)\nlibrary(tidyverse)\nlibrary(DescTools) # Desc() allows you to quick screen data\nlibrary(lavaan) # Desc() allows you to quick screen data\n# options(digits = 3)\n```\n:::\n\n\n\n\n## The Logic of Exploratory Analyses\n\n-   Exploratory analyses attempt to discover hidden structure in data with little to no user input\n    -   Aside from the selection of analysis and estimation\n-   The results from exploratory analyses can be misleading\n    -   If data do not meet assumptions of model or method selected\n    -   If data have quirks that are idiosyncratic to the sample selected\n    -   If some cases are extreme relative to others\n    -   If constraints made by analysis are implausible\n-   Sometimes, exploratory analyses are needed\n    -   Must construct an analysis that capitalizes on the known features of data\n    -   There are better ways to conduct such analyses\n-   Often, exploratory analyses are not needed\n    -   But are conducted anyway – see a lot of reports of scale development that start with the idea that a construct has a certain number of dimensions\n\n# Advanced matrix operations\n\n## Matrix Orthogonality\n\n-   A square matrix $\\Lambda$ is said to be orthogonal if:\n\n$$\n\\mathbf{\\Lambda\\Lambda^T = \\Lambda^T\\Lambda = I}\n$$\n\n-   Orthogonal matrices are characterized by two properties\n    1.  The dot product of all row vector multiples is the zero vector\n        -   Meaning vectors are orthogonal (or uncorrelated)\n    2.  For each row vector, the sum of all elements is one\n        -   Meaning vectors are “normalized”\n-   The matrix above is also called **orthonormal**\n    -   The diagonal is equal to 1 (each vector has a unit length)\n-   Orthonormal matrices are used in principal components and exploratory factor analysis\n\n## Eigenvalues and Eigenvectors\n\n-   A square matrix $\\mathbf{\\Sigma}$ can be decomposed into a set of eigenvalues $\\mathbf{\\lambda}$ and a set of eigenvectors $e$:\n\n$$\n\\mathbf{\\Sigma e} = \\lambda \\mathbf{e}\n$$\n\n-   Each eigenvalue has a corresponding eigenvector\n    -   The number equal to the number of rows/columns of $\\mathbf{\\Sigma}$\n-   Principal components analysis uses eigenvalues and eigenvectors to reconfigure data\n\n## Example: Eigenvalues and Eigenvectors\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Correlation matrix of SAR sR\nsat_corrmat = cor(dataSAT[, c(\"SATV\", \"SATM\")])\n\n## eignvalues and eigenvectors of correlation matrix:\nsat_eigen = eigen(x = sat_corrmat, symmetric = TRUE)\nsat_eigen$values # eigenvalues\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.7752238 0.2247762\n```\n\n\n:::\n\n```{.r .cell-code}\nsat_eigen$vectors # eigenvectors\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]       [,2]\n[1,] 0.7071068 -0.7071068\n[2,] 0.7071068  0.7071068\n```\n\n\n:::\n:::\n\n\n\n\n-   In our SAT sample, the two eigenvalues obtained were:\n\n$$\n\\lambda_1 = 1.775; \n\\lambda_2 = 0.224 \\\\\n$$\n\n-   The two eigenvectors obtained were:\n\n$$\n\\mathbf{e}_1 = \\begin{bmatrix}0.707 \\\\ 0.707\\end{bmatrix};\n\\mathbf{e}_2 = \\begin{bmatrix}-0.707 \\\\ 0.707\\end{bmatrix}\n$$\n\n-   These terms will have much greater meaning principal components analysis\n\n## Spectral Decomposition\n\n-   Using the eigenvalues and eigenvectors, we can reconstruct the original matrix using a spectral decomposition:\n\n$$\n\\mathbf{\\Sigma =}\\sum_{i=1}^{p} \\lambda_i\\mathbf{e}_i \\mathbf{e}_i^T\n$$\n\nwhere i is the index of row/column of square matrix\n\n-   For our example, we can get back to our 2\\*2 original matrix:\n\n$$\n\\mathbf{R}_1 = \\lambda_1 \\mathbf{e}_i \\mathbf{e}_i^T = 1.775 \\begin{bmatrix}0.707 \\\\ 0.707\\end{bmatrix} \\begin{bmatrix}0.707 & 0.707\\end{bmatrix} = \\begin{bmatrix}0.890 & 0.890\\\\ 0.890 & 0.890\\end{bmatrix}\n$$ $$\n\\begin{align}\n\\mathbf{R}_2 &= \\mathbf{R}_1 +\\lambda_1 \\mathbf{e}_i \\mathbf{e}_i^T \\\\\n&= \\begin{bmatrix}0.890 & 0.890\\\\ 0.890 & 0.890\\end{bmatrix}\n + 0.224 \\begin{bmatrix}-0.707 \\\\ 0.707\\end{bmatrix} \\begin{bmatrix}-0.707 & 0.707\\end{bmatrix} \\\\\n&= \\begin{bmatrix}1.000 & 0.780\\\\ 0.780 & 1.000 \\end{bmatrix}\n\\end{align}\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# spectral decomposition\ncorr_rank1 = sat_eigen$values[1] * tcrossprod(sat_eigen$vectors[,1]) #<1>\ncorr_rank1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]      [,2]\n[1,] 0.8876119 0.8876119\n[2,] 0.8876119 0.8876119\n```\n\n\n:::\n:::\n\n\n\n\n1.  `tcrossprod`: $\\mathbf{e}\\mathbf{e}^T$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr_rank2 = corr_rank1 + sat_eigen$values[2] * tcrossprod(sat_eigen$vectors[,2])\ncorr_rank2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]      [,2]\n[1,] 1.0000000 0.7752238\n[2,] 0.7752238 1.0000000\n```\n\n\n:::\n:::\n\n\n\n\n## Additional Eigenvalue Properties\n\n-   The matrix trace is the sum of the eigenvalues:\n\n$$\ntr(\\mathbf\\Sigma) = \\sum_{i=1}^{p}\\lambda_i\n$$\n\n-   In our example, the $tr(\\mathbf R) = 1.775 + 0.224 \\approx 2$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(sat_eigen$values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n\n\n-   The matrix determinant can be found by the product of the eigenvalues\n\n$$\n|\\mathbf\\Sigma| = \\prod_{i=1}^p \\lambda_i\n$$\n\n-   In our example, the $|\\mathbf R| = 1.775 * 0.224 \\approx .3976$\n\n# AN INTRODUCTION TO PRINCIPAL COMPONENTS ANALYSIS\n\n## PCA Overview\n\n1.  **Principal Components Analysis** (PCA) is a method for re-expressing the covariance (or often correlation) between a set of variables\n\n    -   The re-expression comes from creating a set of new variables (linear combinations) of the original variables\n\n2.  PCA has two objectives:\n\n    1.  Data reduction - Moving from many original variables down to a few \"components\"\n\n    2.  Interpretation - Determining which original variables contribute most to the new \"components\"\n\n## Goals of PCA\n\n-   The **goal** of PCA is to find a set of k principal components (composite variables) that:\n    -   Is much smaller in number than the original set of V variables\n    -   Accounts for nearly all of the total variance\n        -   Total variance = trace of covariance/correlation matrix\n-   If these two goals can be accomplished, then the set of k principal components contains almost as much information as the original V variables\n    -   Meaning – the components can now replace the original variables in any subsequent analyses\n\n## Questions when using PCA\n\n-   PCA analyses proceed by seeking the answers to two questions:\n    1.  How many components (new variables) are needed to “adequately” represent the original data?\n        -   The term adequately is fuzzy (and will be in the analysis)\n    2.  (once #1 has been answered): What does each component represent?\n        -   The term “represent” is also fuzzy\n\n## PCA Features\n\n-   PCA often reveals relationships between variables that were not previously suspected\n    -   New interpretations of data and variables often stem from PCA\n-   PCA usually serves as more of a means to an end rather than an end it itself\n    -   Components (the new variables) are often used in other statistical techniques\n        -   Multiple regression/ANOVA\n        -   Cluster analysis\n-   Unfortunately, PCA is often intermixed with Exploratory Factor Analysis\n    -   Don’t. Please don’t. Please make it stop.\n\n## PCA Details\n\n-   Notation: $Z$ are our new components and $\\mathbf Y$ is our original data matrix (with N observations and V variables)\n    -   We will let p be our index for a subject\n-   The new components are linear combinations:\n\n$$\n\\begin{array}{c}\nZ_{p 1}=\\mathbf{e}_{1}^{T} \\mathbf{Y}=e_{11} Y_{p 1}+e_{21} Y_{p 2}+\\cdots+e_{V 1} Y_{p V} \\\\\nZ_{p 2}=\\mathbf{e}_{2}^{T} \\mathbf{Y}=e_{12} Y_{p 1}+e_{22} Y_{p 2}+\\cdots+e_{V 2} Y_{p V} \\\\\n\\vdots \\\\\nZ_{p V}=\\mathbf{e}_{V}^{T} \\mathbf{Y}=e_{1 V} Y_{p 1}+e_{2 V} Y_{p 2}+\\cdots+e_{V V} Y_{p V}\n\\end{array}\n$$\n\n-   The weights of the components ($e_{jk}$) come from the eigenvectors of the covariance or correlation matrix for component k and variable j\n\n## Details about the components\n\n-   The components ($Z$) are formed by the weights of the eigenvectors of the covariance or correlation matrix of the original data\n\n    -   The variance of a component is given by the eigenvalue associated with the eigenvector for the component\n\n-   Using the eigenvalue and eigenvectors means:\n\n    -   Each successive component has lower variance\n        -   Var(Z1) \\> Var(Z2) \\> … \\> Var(Zv)\n    -   All components are uncorrelated\n    -   The sum of the variances of the principal components is equal to the total variance:\n\n    $$\n    \\sum_{v=1}^{V} \\operatorname{Var}\\left(Z_{v}\\right)=\\operatorname{tr} \\mathbf{\\Sigma}=\\sum_{v=1}^{V} \\lambda_{v}\n    $$\n\n## PCA on our example\n\n1.  We will now conduct a PCA on the correlation matrix of our sample data\n    -   This example is given for demonstration purposes – typically we will not do PCA on small numbers of variables\n\n![](images/clipboard-2518475766.png){fig-align=\"center\" width=\"670\"}\n\n## PCA in R\n\n-   The R function that does principal components is called `prcomp()`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata01 <- dataSAT[, c(\"SATV\", \"SATM\")]\n# PCA of correlation matrix \nsat_pca_corr = prcomp(x = data01, scale. = TRUE)\n\n# show the results\nsat_pca_corr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandard deviations (1, .., p=2):\n[1] 1.3323753 0.4741057\n\nRotation (n x k) = (2 x 2):\n            PC1        PC2\nSATV -0.7071068  0.7071068\nSATM -0.7071068 -0.7071068\n```\n\n\n:::\n\n```{.r .cell-code}\n# show the summary statistics\nsummary(sat_pca_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2\nStandard deviation     1.3324 0.4741\nProportion of Variance 0.8876 0.1124\nCumulative Proportion  0.8876 1.0000\n```\n\n\n:::\n:::\n\n\n\n\n## Graphical Representation\n\n-   Plotting the components and the original data side by side reveals the nature of PCA:\n    -   Shown from PCA of covariance matrix\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n#create same analysis but with covariance matrix (for visual) scale.=FALSE (covariance matrix) \nsat_pca_cov = prcomp(x = data01, scale. = FALSE)\n\n#create augmented data matrix for plot\ndata01a = data01\ndata01a$type = \"Raw\"\n\ndata01b = data.frame(SATV = sat_pca_cov$x[,1], SATM = sat_pca_cov$x[,2], type=\"PC\")\ndata01c = rbind(data01a, data01b)\n\nplot(x = data01c$SATV, y = data01c$SATM, ylab = \"SATM/PC2\", xlab = \"SATV/PC1\", cex.main=1.5, frame.plot=FALSE, col=ifelse(data01c$type==\"Raw\", \"red\", \"blue\"))\nlegend(0, 400, pch=1, col=c(\"red\", \"blue\"), c(\"Data\", \"PCs\"), bty=\"o\",  box.col=\"darkgreen\", cex=1.5)\n```\n\n::: {.cell-output-display}\n![](Lecture12_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=1728}\n:::\n:::\n\n\n\n\n## An empirical example: The Growth of Gambling Access\n\n-   In past 25 years:\n    -   An exponential increase in the accessibility of gambling\n    -   An increased rate of with problem or pathological gambling (Volberg, 2002, Welte et al., 2009)\n-   Hence, there is a need to better:\n    -   Understand the underlying causes of the disorder\n    -   Reliably identify potential pathological gamblers\n    -   Provide effective treatment interventions\n\n## Pathological Gambling: DSM Definition\n\n-   To be diagnosed as a pathological gambler, an individual must meet **5 of 10 defined criteria**:\n\n::: columns\n::: {.column width=\"50%\"}\n1.  Is preoccupied with gambling\n2.  Needs to gamble with increasing amounts of money in order to achieve the desired excitement\n3.  Has repeated unsuccessful efforts to control, cut back, or stop gambling\n4.  Is restless or irritable when attempting to cut down or stop gambling\n5.  Gambles as a way of escaping from problems or relieving a dysphoric mood\n:::\n\n::: {.column width=\"50%\"}\n6.  After losing money gambling, often returns another day to get even (“chasing” one’s losses)\n7.  Lies to family members, therapist, or others to conceal the extent of involvement with gambling\n8.  Has committed illegal acts such as forgery, fraud, theft, or embezzlement to finance gambling\n9.  Has jeopardized or lost a significant relationship, job, or educational or career opportunity because of gambling\n10. Relies on others to provide money to relieve a desperate financial situation caused by gambling\n:::\n:::\n\n## Research on Pathological Gambling\n\n-   In order to study the etiology of pathological gambling, more variability in responses was needed\n-   The Gambling Research Instrument (Feasel, Henson, & Jones,2002) was created with 41 Likert-type items\n    -   Items were developed to measure each criterion\n-   Example items (ratings: Strongly Disagree to Strongly Agree):\n    -   I worry that I am spending too much money on gambling (C3)\n    -   There are few things I would rather do than gamble (C1)\n-   The instrument was used on a sample of experienced gamblers from a riverboat casino in a Flat Midwestern State\n    -   Casino patrons were solicited after playing roulette\n\n## The GRI Items\n\n-   The Gambling Research Instrument (GRI) used a 6-point Likert scale:\n    -   1: Strongly Disagree\n    -   2: Disagree\n    -   3: Slightly Disagree\n    -   4: Slightly Agree\n    -   5: Agree\n    -   6: Strongly Agree\n-   To meet the assumptions of factor analysis, we will treat these responses as being continuous\n    -   This is tenuous at best, but often is the case in factor analysis\n    -   Categorical items would be better….but you’d need another course for how to do that\n        -   Hint: Item Response Models\n\n## The Sample\n\n-   Data were collected from two sources:\n    -   112 “experienced” gamblers\n        -   Many from an actual casino\n    -   1192 college students from a “rectangular” midwestern state\n        -   Many never gambled before\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata02 = read.csv(file=\"gambling_lecture12.csv\",header=TRUE)\n#listwise removal of missing data (common in PCA -- but still a problem)\ndata02a = data02[complete.cases(data02),]\ndim(data02a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1333   10\n```\n\n\n:::\n:::\n\n\n\n\n-   Today, we will combine both samples and treat them as homogenous – one sample of 1304 subjects\n\n## Final 10 items on the scale\n\n| Item | Criterion | Question |\n|------|-----------|----------|\n| GRI1  | 3    |I would like to cut back on my gambling.          |\n| GRI3  | 6    |If I lost a lot of money gambling one day, I would be more likely to want to play again the following day.          |\n| GRI5  | 2    |I find it necessary to gamble with larger amounts of money (than when I first gambled) for gambling to be exciting.          |\n| GRI9  | 4    |I feel restless when I try to cut down or stop gambling.          |\n| GRI10 | 1    |It bothers me when I have no money to gamble.          |\n| GRI13 | 3    |I find it difficult to stop gambling.          |\n| GRI14 | 2    |I am drawn more by the thrill of gambling than by the money I could win.          |\n| GRI18 | 9    |My family, coworkers, or others who are close to me disapprove of my gambling.          |\n| GRI21 | 1    |It is hard to get my mind off gambling.          |\n| GRI23 | 5    |I gamble to improve my mood.          |\n\n  \n## Question #1: How Many Components?\n\n- To answer the question of how many components, two methods are used:\n    - Scree plot of eigenvalues (looking for the “elbow”)\n    - Variance accounted for (should be > 70%)\n- We will go with 4 components: (variance accounted for VAC = 75%)\n- Variance accounted for is for the total sample variance\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#analysis of covariance matrix of gambling data items\ngambling_pca_cov = prcomp(x = data02a, scale. = FALSE) \n# gambling_pca_cov\nsummary(gambling_pca_cov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2    PC3     PC4     PC5     PC6     PC7\nStandard deviation     2.0485 1.3229 1.0883 0.83608 0.75096 0.73365 0.68616\nProportion of Variance 0.4043 0.1686 0.1141 0.06736 0.05434 0.05186 0.04537\nCumulative Proportion  0.4043 0.5730 0.6871 0.75447 0.80881 0.86067 0.90604\n                           PC8     PC9    PC10\nStandard deviation     0.64836 0.58230 0.46438\nProportion of Variance 0.04051 0.03267 0.02078\nCumulative Proportion  0.94655 0.97922 1.00000\n```\n\n\n:::\n:::\n\n\n\n## Plots to Answer How Many Components\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nprop_var = t(summary(gambling_pca_cov)$importance[2:3,])\n#creating a scree plot and a proportion of variance plot\n\npar(mfrow = c(1,2))\nplot(gambling_pca_cov, type=\"l\", main = \"Scree Plot of PCA Eigenvalues\", lwd = 5)\nmatplot(prop_var, type=\"l\", main = \"Proportion of Variance Explained by Component\", lwd = 5)\nlegend(x=5, y=.5, legend = c(\"Component Variance\", \"Cumulative Variance\"), lty = 1:2, lwd=5, col=1:2)\n```\n\n::: {.cell-output-display}\n![](Lecture12_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=1536}\n:::\n:::\n\n\n\n\n## Question #2: What Does Each Component Represent?\n\n-   To answer question #2 – we look at the weights of the eigenvectors (here is the unrotated solution)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(gambling_pca_cov$rotation, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       PC1    PC2    PC3    PC4    PC5    PC6    PC7    PC8    PC9   PC10\nX1  -0.313  0.105  0.166 -0.844  0.365 -0.090  0.090  0.002  0.028  0.040\nX3  -0.226  0.078  0.178 -0.134 -0.525  0.680  0.343 -0.192 -0.015  0.026\nX5  -0.320  0.094  0.229  0.026 -0.492 -0.626 -0.090 -0.395 -0.044  0.187\nX9  -0.243  0.087  0.160  0.031 -0.117 -0.062 -0.153  0.152  0.045 -0.917\nX10 -0.280  0.087  0.235  0.085 -0.195 -0.026 -0.093  0.842 -0.027  0.307\nX13 -0.329  0.156  0.186  0.220  0.326  0.295 -0.505 -0.225 -0.524  0.101\nX14 -0.449 -0.862 -0.231  0.006 -0.004  0.026 -0.037 -0.001 -0.004  0.002\nX18 -0.347  0.405 -0.834 -0.028 -0.100 -0.019  0.009  0.053 -0.074  0.002\nX21 -0.272  0.137  0.062  0.198  0.179  0.155 -0.250 -0.143  0.842  0.128\nX23 -0.326  0.098  0.139  0.416  0.386 -0.147  0.718 -0.025 -0.071 -0.033\n```\n\n\n:::\n:::\n\n\n\n\n## Final Result: Four Principal Components\n\n-   Using the weights of the eigenvectors, we can create four new variables – the four principal components\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(gambling_pca_cov$x[, 1:4], 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          PC1       PC2       PC3        PC4\n1  -2.5448889 1.2879590 1.5823332 -1.8230315\n2   2.1851408 0.3646125 0.1984711  0.2642768\n3  -0.6179050 0.6644431 0.2403178  0.3784284\n4   0.1443078 1.1269409 1.5393139 -0.1311429\n5   0.1443078 1.1269409 1.5393139 -0.1311429\n6   2.1851408 0.3646125 0.1984711  0.2642768\n7   2.1851408 0.3646125 0.1984711  0.2642768\n8   2.1851408 0.3646125 0.1984711  0.2642768\n9   1.8724936 0.4692059 0.3647580 -0.5794583\n10  1.8724936 0.4692059 0.3647580 -0.5794583\n```\n\n\n:::\n:::\n\n\n\n\n- Each of these is uncorrelated with each other\n  -   The variance of each is equal to the corresponding eigenvalue\n  \n- We would then use these in subsequent analyses\n\n## PCA Summary\n\n-   PCA is a **data reduction** technique that relies on the mathematical properties of eigenvalues and eigenvectors\n    -   Used to create new variables (small number) out of the old data (lots of variables)、\n    -   The new variables are principal components (they are not factor scores)\n    \n-   PCA appeared first in the psychometric literature\n    -   Many “factor analysis” methods used variants of PCA before likelihood-based statistics were available\n    \n-   Currently, PCA (or variants) methods are the default option in SPSS and SAS (PROC FACTOR)    \n\n## Potentially Solvable Statistical Issues in PCA\n\n- The typical PCA analysis also has a few statistical concerns\n    -  Some of these can be solved if you know what you are doing\n    -  The typical analysis (using program defaults) does not solve these\n- Missing data is omitted using listwise deletion – biases possible\n    -  Could use ML to estimate covariance matrix, but then would have to assume\nmultivariate normality\n    -  Could use MI to impute data\n- The distributions of variables can be anything…but variables\nwith much larger variances will look like they contribute more\nto each component\n    -  Could standardize variables – but some can’t be standardized easily (think gender)\n- The lack of standard errors makes the component weights\n(eigenvector elements)\nhard to interpret\n    -  Can use a resampling/bootstrap analysis to get SEs (but not easy to do)\n    \n## (Unsolvable) Issues with PCA\n\n- My issues with PCA involve the two questions in need of\nanswers for any use of PCA:\n1. The number of components needed is not based on a\nstatistical hypothesis test and hence is subjective\n    -  Variance accounted for is a descriptive measure\n    -  No statistical test for whether an additional component significantly accounts\nfor more variance\n2. The relative meaning of each component is questionable\nat best and hence is subjective\n    -  Typical packages provide no standard errors for each eigenvector weight (can\nbe obtained in bootstrap analyses)\n    -  No definitive answer for component composition\n- In sum, I feel it is very easy to be misled (or purposefully\nmislead) with PCA\n\n# EXPLORATORY FACTOR ANALYSIS\n\n## Primary Purpose of EFA\n\n-  **EFA**: “Determine nature and number of latent variables that account\nfor observed variation and covariation among set of observed\nindicators (≈ items or variables)”\n    -  In other words, what causes these observed responses?\n    -  Summarize patterns of correlation among indicators\n    -  Solution is an end (i.e., is of interest) in and of itself\n-  Compared with **PCA**: “Reduce multiple observed variables into fewer\ncomponents that summarize their variance”\n    -  In other words, how can I abbreviate this set of variables?\n    -  Solution is usually a means to an end\n    \n## Methods for EFA\n\n-   You will see many different types of methods for “extraction” of factors in EFA\n    - Many are PCA-based\n    - Most were developed before computers became relevant or likelihood theory was developed\n    \n-   You can ignore all of them and focus on one:\n    - Only Use Maximum Likelihood for EFA\n    \n-   The maximum likelihood method of EFA extraction:\n    -  Uses the same log-likelihood as confirmatory factor analyses/SEM\n        - Default assumption: multivariate normal distribution of data\n    -  Provides consistent estimates with good statistical properties (assuming you have a\nlarge enough sample)\n    -  Missing data using all the data that was observed (MAR)\n    -  Is consistent with modern statistical practices    \n\n## Questions when using EFA\n\n-   EFAs proceed by seeking the answers to two questions: (the same questions posed in PCA; but with different terms)\n    1. How many latent factors are needed to “adequately” represent the original data?\n        - “Adequately” = does a given EFA model fit well?\n    2. (once #1 has been answered): What does each factor represent?\n        - The term “represent” is fuzzy\n        \n## The Syntax of Factor Analysis\n\n-   Factor analysis works by hypothesizing that a set of latent factors helps to determine a person’s response to a set of variables\n\n    -   This can be explained by a system of simultaneous linear models\n    -   Here Y = observed data, p = person, v = variable, F = factor score (Q factors)\n\n$$\n\\begin{array}{c}\nY_{p 1}=\\mu_{y_{1}}+\\lambda_{11} F_{p 1}+\\lambda_{12} F_{p 2}+\\cdots+\\lambda_{1 Q} F_{p Q}+e_{p 1} \\\\\nY_{p 2}=\\mu_{y_{2}}+\\lambda_{21} F_{p 1}+\\lambda_{22} F_{p 2}+\\cdots+\\lambda_{2 Q} F_{p Q}+e_{p 2} \\\\\n\\vdots \\\\\nY_{p V}=\\mu_{y_{V}}+\\lambda_{V 1} F_{p 1}+\\lambda_{V 2} F_{p 2}+\\cdots+\\lambda_{V Q} F_{p Q}+e_{p V}\n\\end{array}   \n$$\n\n-   $\\mu_{y_v}$ = mean for variable $v$;\n-   $\\lambda_{vq}$ = factor loading for variable v onto factor f (regression slope) \n    -   Factors are assumed distributed MVN with zero mean and (for EFA) identity covariance matrix (uncorrelated factors – to start)\n-   $e_{pv}$  = residual for person p and variable v;\n    -   Residuals are assumed distributed MVN (across items) with a zero mean and a diagonal covariance matrix $\\mathbf\\Psi$ containing the unique variances\n-   Often, this gets shortened into matrix form:\n\n$$\n\\mathbf{Y_p = \\mu_Y+\\Lambda F_p^T + e_p}\n$$\n\n## How Maximum Likelihood EFA Works\n\n-   Maximum likelihood EFA assumes the data follow a multivariate normal distribution\n    -   The basis for the log-likelihood function (same log-likelihood we have used in every analysis to this point)\n    \n-   The log-likelihood function depends on two sets of parameters: the mean vector and the covariance matrix    \n    -   Mean vector is saturated (just uses the item means for item intercepts) – so it is often not thought of in analysis\n        -   Denoted as $\\boldsymbol\\mu_y = \\boldsymbol\\mu_I$\n        \n    -   Covariance matrix is what gives \"factor structure\"\n        -   EFA models provide a structure for the covariance matrix\n        \n## The EFA Model for the Covariance Matrix\n\n-   The covariance matrix is modeled based on how it would look if a set of hypothetical (latent) factors had caused the data\n\n-   For an analysis measuring $F$ factors, each item in the EFA:\n    -   Has 1 unique variance parameter\n    -   Has F factor loadings\n    \n-   The initial estimation of factor loadings is conducted based on the assumption of uncorrelated factors\n    -   Assumption is dubious at best – yet is the cornerstone of the analysis\n    \n## Model Implied Covariance Matrix\n\n-   The factor model implied covariance matrix is $\\boldsymbol{\\Sigma_Y=\\Lambda\\Phi\\Lambda^T+\\Psi}$\n    -   Where:\n        -  $\\boldsymbol{\\Sigma_Y}$ = model implied covariance matrix of the observed data (size $I \\times I$)\n        -  $\\boldsymbol{\\Lambda}$ = matrix of factor loadings (size $I \\times F$)\n            - In EFA: all terms in $\\boldsymbol{\\Lambda}$ are estimated\n        - $\\boldsymbol{\\Phi}$  = factor covariance matrix (size $F \\times F$)\n        – In EFA: $\\boldsymbol{\\Phi}$ = $\\boldsymbol{I}$ (all factors have variances of 1 and covariances of 0)\n            - In CFA: this is estimated\n        - $\\boldsymbol{\\Psi}$ = matrix of unique (residual) variances (size $I \\times I$)\n            - In EFA: $\\boldsymbol{\\Psi}$ is diagonal by default (no residual covariances)",
    "supporting": [
      "Lecture12_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}