---
title: "Publications | Jihong Zhang"
sidebar: false
toc: true
toc-location: left
toc-depth: 3
execute: 
  eval: true
  echo: false
format: 
  html:
    title-block-banner: false
    code-tools: false
    code-fold: false
    comments: false
freeze: true
---

```{r setup}
#| message: false
library(scholar)
library(ggplot2)
library(dplyr)
library(stringr)
library(htmltools)
```

```{r compile_data}
#| include: false

# "MbRDAB4AAAAJ" is my Google scholar id, which can be found in your Google scholar URL address
# For example, my Google scholar webpage has the URL "https://scholar.google.com/citations?user=MbRDAB4AAAAJ&hl=zh-CN"
# Text after "user=" is your ID
# get_publication_url(id = "MbRDAB4AAAAJ", pub_id = pubs$pubid[2])
pubs <- scholar::get_publications("MbRDAB4AAAAJ", sortby = "year") 
# generate the path for pdf
# Replace ":" or "?" with "_"
pubs <- pubs |> 
  mutate(
    URL = get_article_scholar_url(id = "MbRDAB4AAAAJ", pubid = pubid)
  ) |> 
  arrange(desc(year)) |> 
  mutate(
    pubs_formated = paste0(str_replace(format_publications("MbRDAB4AAAAJ"), 
                                       "Zhang, J.", "**Zhang, J.**"))
  ) |> 
  mutate(publication_pdf_path = paste0("publications/", year, "/", str_replace(title, "[:|?]", "_"), ".pdf")) |> 
  mutate(
    pubs_formated = str_replace(pubs_formated, title, paste0("[", title, "](", publication_pdf_path, ")"))
  ) |> 
  select(title:number, year, pubs_formated, URL)
```

```{r}
#| eval: false

## Debug
publication_pdf_path <- list.files("publications", full.names = TRUE, recursive = TRUE)
pubs$pubs_formated <- str_replace(pubs$pubs_formated, "Math anxiety is associated with skipping problems and less help-seeking behavior after error commission", 
                                  paste0("[Math anxiety is associated with skipping problems and less help-seeking behavior after error commission](", publication_pdf_path[2], ")"))
```

```{r total_paper}
## Dynamically display the histogram of number of publications
pubs_count_byyear <- pubs |> 
  count(year) |> 
  arrange(desc(year)) |> 
  mutate(n_cum = cumsum(n))

# total_publication <- paste0("In total, I've published ", nrow(pubs), " papers. ")
# p(total_publication)
```

```{r dynamic_plot}
#| fig-height: 4
#| warning: false
#| message: false
library(plotly)
pubs_count_ts <- pubs_count_byyear |> arrange(year) |> mutate(n_cum = cumsum(n))

## Refer to https://rstudio.github.io/dygraphs/
t <- list(
  family = "Abel",
  size = 14,
  color = '#404041')
plot_ly(data = pubs_count_ts, x=~year,
        showlegend = FALSE) |> 
  add_bars(y=~n, color = I("grey"), opacity = .3) |> 
  add_trace(type = "scatter", mode = "lines+markers", y=~n, color = I("maroon")) |> 
  add_trace(type = "scatter", mode = "lines+markers", y=~n_cum, color = I("darkseagreen")) |> 
  add_text(y=~n_cum + 2, text=~n_cum, color = I("darkseagreen")) |> 
  layout(
    paper_bgcolor = "#FAF9F6",
    plot_bgcolor='#FAF9F6',
    title = "",
    xaxis = list(title = "Line Plot: Number of Publications per Year (<span style='color: maroon'>Red</span>) and Cumulative number (<span style='color: darkseagreen'>Green</span>)"),
    yaxis = list(title = ""),
    font = t
  ) 
```

------------------------------------------------------------------------

```{r}
#| echo: false
#| results: asis
#| warning: false
# https://github.com/sonsoleslp/sonsoleslp.github.io/blob/main/publications.qmd

leading_year_icon = ""
pubs_formated <- pubs$pubs_formated
for (y in 1:nrow(pubs_count_byyear)) {
  ## Create a year tag
  year_tag <- paste0(leading_year_icon, pubs_count_byyear$year[y], leading_year_icon)
  print(p(year_tag, style="color: #72994E; font-family: 'Abel'; text-align: center; font-size: 1.45em;"))
  
  ## Per each year, calculate the index of publication
  index_min = ifelse(y == 1, 1, pubs_count_byyear$n_cum[y-1] + 1)
  index_max = pubs_count_byyear$n_cum[y]
  
  pubs_list_peryear <- list()
  j = 0
  length(pubs_list_peryear) <- (index_max - index_min) + 1
  for (i in index_min:index_max) {
    j = j + 1
    
    cat("\n")
    
    pubs_list_peryear[[j]] <- tags$li(pubs_formated[i], 
                                      a(class = "fa-brands fa-google-scholar fa-sm", 
                                        href = pubs$URL[i], 
                                        style="color: #74C0FC"), 
                                      style="font-size: .9em;")
    }
  
  ## Print the publication list per year
  print(tags$ul(pubs_list_peryear, style="padding-left: 3rem;"))
}
```

## {{< fa brands apple >}} Citations

@fig-citation shows the citations.

```{r}
#| label: fig-citation
#| fig-cap: "Histogram of Citations by Year"
cit <- get_citation_history('MbRDAB4AAAAJ') # the Google Scholar ID
ggplot(cit,aes(x=year,y=cites))+
  geom_bar(stat='identity')+
  geom_label(aes(label = cites)) +
  theme_classic()+
  xlab('Year of citation')+
  ylab('Google Scholar\n cites')+
  annotate('text',label=format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),x=-Inf,y=Inf,vjust=1.5,hjust=-0.05,size=3,colour='gray')
```
