---
title: "Regularization for Variable Selection in Multidimensional Factor and Network Models"
date: 2024-08-03
categories: 
  - Working
author: ["Jihong Zhang", "Xinya Liang", "Jiaying Chen"]
format: html
---

## AERA 2025 Proposal

The field of psychometrics often uses various models, such as network models and factor analysis, to analyze complex data. Although these methods offer different interpretations, they share similar characteristics. Network modeling explores partial correlations to identify critical nodes and pathways (Epskamp et al., 2017), while factor analysis reveals the underlying structure that explains the observed covariance of variables (Lawley et al., 1962). Both methods employ regularization techniques to enhance model selection and prevent overfitting, which is crucial for handling multidimensional data (Epskamp et al., 2018; Jacobucci et al., 2016). This study presents a comparative analysis of these methods, with a special focus on their performance in terms of model fitting and variable selection. The main motivation for this comparison stems from the prevalence of factor models used in the design of empirical psychometric data, which usually assume dimensionality. However, the actual underlying structure of these data is often not well understood, which raises questions about the validity of network models in settings traditionally dominated by factor analysis. By testing whether network analysis can robustly handle data generated under the assumptions of factor models, this study can significantly broaden the understanding and application of network approaches in psychometrics (Borsboom & Cramer, 2013).
