{
  "hash": "57b127b31da9f8e83b1fde7cb78cbf75",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 03: Introduction to One-way ANOVA\"\nsubtitle: \"Experimental Design in Education\"\ndate: \"2025-08-18\"\nexecute: \n  eval: false\n  echo: true\n  warning: false\nformat: \n  html:\n    code-tools: true\n    code-line-numbers: false\n    code-fold: false\n    number-offset: 1\n    fig.width: 10\n    fig-align: center\n    message: false\n    grid:\n      sidebar-width: 350px\n  uark-revealjs:\n    chalkboard: true\n    embed-resources: false\n    code-fold: false\n    number-sections: true\n    number-depth: 1\n    footer: \"ESRM 64503\"\n    slide-number: c/t\n    tbl-colwidths: auto\n    scrollable: true\n    output-file: slides-index.html\n    mermaid:\n      theme: forest  \n---\n\n\n\n\n\n\n## Lecture Outline\n\n-   Homework assignment\n-   Introduction to ANOVA\n    -   Why use ANOVA instead of multiple t-tests?\n    -   Logic and components of ANOVA\n    -   Steps and assumptions in ANOVA\n    -   Example scenario and real-world applications\n-   Performing ANOVA in R\n    -   Checking homogeneity of variance\n    -   Post-hoc analysis\n    -   Using weights in ANOVA\n    -   Where to find weights for ANOVA\n-   Conclusion\n\n# Homework 1\n\n## Let's walk through HW1\n\n# One-Way ANOVA\n\n## Introduction\n\n-   Overview of ANOVA and its applications.\n-   Used for comparing means across multiple groups.\n-   Explanation of why ANOVA is essential in statistical analysis.\n\n## ANOVA Basics\n\n-   **Analysis of Variance (ANOVA)** is a statistical method for comparing means across three or more groups.\n-   When comparing only 2 groups, a t-test is typically used (though mathematically equivalent to ANOVA with 2 groups).\n-   When comparing 3 or more groups, ANOVA using the F-test is the appropriate method to avoid inflating Type I error.\n\n## Why Use ANOVA Instead of Multiple t-tests?\n\n1.  **Computational efficiency**: As the number of groups increases, the number of pairwise comparisons grows rapidly (k groups require k(k-1)/2 comparisons).\n2.  **Controls Type I error**: Multiple t-tests inflate the family-wise error rate. For example, with 4 groups and α = 0.05, conducting 6 t-tests results in an actual error rate of approximately 0.26, not 0.05.\n3.  **Omnibus test**: ANOVA provides a single test to determine if any group differences exist before conducting pairwise comparisons.\n4.  **Statistical power**: ANOVA is more powerful than multiple t-tests when properly applied with post-hoc corrections.\n\n## Logic of ANOVA\n\n-   ANOVA compares group means by analyzing [variance components]{.underline}.\n-   Two independent variance estimates:\n    1.  **Between-group variability**: Differences among group means (reflects treatment effect)\n    2.  **Within-group variability**: Differences within each group (reflects random error or chance)\n-   If the between-group variability is substantially larger than the within-group variability, we conclude that groups differ significantly.\n\n## Components of ANOVA\n\n1.  **Total Sum of Squares** ($SS_{total}$): Total variability in the outcome variable across all observations.\n2.  **Sum of Squares Between** ($SS_{between}$): Variability attributable to differences between group means (systematic variation).\n3.  **Sum of Squares Within** ($SS_{within}$): Variability within groups, representing random error (unsystematic variation).\n    -   Key relationship: $SS_{total} = SS_{between} + SS_{within}$\n\n------------------------------------------------------------------------\n\n### If $SS_{between}$ \\> $SS_{within}$ ...\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ESRM64103_Lecture03_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n#### R output:\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)    \ngroup        1 218.42  218.42   264.1 <2e-16 ***\nResiduals   38  31.43    0.83                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Interpretation**: With small within-group variability (SD = 1) and clear separation between groups (means of 20 and 25), the F-statistic is large and highly significant. The between-group variance substantially exceeds the within-group variance, providing strong evidence that the groups differ.\n\n------------------------------------------------------------------------\n\n### If $SS_{between}$ \\< $SS_{within}$ ...\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ESRM64103_Lecture03_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n#### R output:\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \ngroup        1  113.4  113.43   5.485 0.0245 *\nResiduals   38  785.8   20.68                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Interpretation**: With larger within-group variability (SD = 5), the overlap between groups increases. Even though the between-group variance remains the same, it is now smaller relative to the within-group variance. This results in a smaller F-statistic and reduced statistical power to detect group differences.\n\n## Practical Steps in One-way ANOVA\n\n1.  Compute the total variability in the outcome variable.\n2.  Partition the total variability into between-group (model) and within-group (error) components.\n3.  Calculate the F-statistic: $F_{obs} = \\frac{SS_{between}/df_{between}}{SS_{within}/df_{within}}=  \\frac{MS_{between}}{MS_{within}}$\n4.  Construct the ANOVA table, set the alpha level (typically 0.05), and draw conclusions based on the p-value.\n5.  Check the homogeneity of variance assumption (Levene's test or Bartlett's test).\n6.  If the overall F-test is significant, conduct post-hoc pairwise comparisons (e.g., Tukey HSD) to identify which specific groups differ.\n\n## Assumptions of ANOVA\n\n1.   Homogeneity of variance (homoscedasticity).\n2.   Independence of observations.\n3.   Normality of residuals.\n\n## Homogeneity of Variance\n\n-   **Assumption**: ANOVA assumes that the variance of the outcome variable is approximately equal across all groups (homoscedasticity).\n-   **Why it matters**: When variances differ substantially across groups, the F-test can become either too liberal (inflated Type I error) or too conservative (reduced power).\n-   **Checking the assumption**: Use visual inspection (boxplots), Levene's test, or Bartlett's test to assess variance equality before interpreting ANOVA results.\n\n::: callout-note\n## We will talk more details about this in the next lecture\n:::\n\n## Methods to Check Homogeneity of Variance\n\n-   **Levene’s Test**: Tests for equal variances across groups.\n-   **Bartlett’s Test**: Specifically tests for homogeneity in normally distributed data.\n-   **Visual Inspection**: Boxplots can help assess variance equality.\n-   Graph: Example of equal and unequal variance in boxplots.\n\n## When Homogeneity of Variance Is Violated\n\n1. **Welch's ANOVA** (Welch's F-test)\n   - Specifically designed for unequal variances\n   - Adjusts degrees of freedom to account for heteroscedasticity\n   - Generally preferred first option when HoV is violated\n\n2. **Brown-Forsythe Test**\n   - Another robust alternative to traditional ANOVA\n   - Less affected by unequal variances than standard F-test\n\n3. **Non-parametric Alternatives**\n   - Kruskal-Wallis test (non-parametric equivalent to one-way ANOVA)\n   - Does not assume equal variances or normality\n   - Tests for differences in distributions rather than means\n\n# Example: One-way ANOVA in R\n\n## Example Scenario\n\n-   **Research Aim**: Investigating the effect of a teaching intervention on children's [verbal acquisition]{.underline}.\n-   **IV (Factor):** Intervention groups (G1, G2, G3, Control).\n-   **DV:** Verbal acquisition scores.\n-   **Hypotheses:**\n    -   $H_0$: $\\mu_{Control} = \\mu_{G1} = \\mu_{G2} = \\mu_{G3}$\n    -   $H_A$: At least two group means differ.\n\n## Performing ANOVA in R\n\n### Load Libraries\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(car) # used for leveneTest; install.packages(\"car\")\n```\n:::\n\n\n\n\n\n\n### Generate Sample Data\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nrnorm(10, 20, 10) # generate 10 data points from a normal distribution with mean = 20 and SD = 10\n```\n:::\n\n\n\n\n\n\n**Explanation**: The `rnorm()` function generates random values from a normal distribution. The `set.seed()` function ensures reproducibility by fixing the random number generation sequence.\n\n-   Context: This example focuses on whether three different teaching methods (labeled as G1, G2, G3) affect students' test scores.\n\n-   In total, 40 students are assigned to three teaching groups and one control group. Each group has 10 students.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n# Create dataset with EQUAL variances (SD = 5 for all groups)\ndata <- data.frame(\n  group = rep(c(\"G1\", \"G2\", \"G3\", \"Control\"), each = 10),\n  score = c(rnorm(10, 20, 5), rnorm(10, 25, 5), rnorm(10, 30, 5), rnorm(10, 22, 5))\n)\n# Create dataset with UNEQUAL variances (SD varies from 0.1 to 10 across groups)\ndata_unequal <- data.frame(\n  group = rep(c(\"G1\", \"G2\", \"G3\", \"Control\"), each = 10),\n  score = c(rnorm(10, 20, 10), rnorm(10, 25, 5), rnorm(10, 30, 1), rnorm(10, 22, .1))\n)\n```\n:::\n\n\n\n\n\n\n**Note**: We create two datasets to demonstrate the importance of homogeneity of variance:\n- `data`: Equal variances (homoscedastic) - meets ANOVA assumptions\n- `data_unequal`: Unequal variances (heteroscedastic) - violates ANOVA assumptions\n\n------------------------------------------------------------------------\n\n### Conduct ANOVA Test\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ANOVA with equal variances\nanova_result <- aov(score ~ group, data = data)\nsummary(anova_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \ngroup        3  724.1  241.37   11.45 2.04e-05 ***\nResiduals   36  759.2   21.09                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# ANOVA with unequal variances\nanova_result2 <- aov(score ~ group, data = data_unequal)\nsummary(anova_result2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \ngroup        3   1413   470.9   19.14 1.37e-07 ***\nResiduals   36    886    24.6                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Comparison**:\n- Both ANOVAs show significant F-statistics (p < 0.05), indicating group differences\n- However, the unequal variance dataset violates ANOVA assumptions, making these results potentially unreliable\n- For `data_unequal`, we should use Welch's ANOVA instead: `oneway.test(score ~ group, data = data_unequal)`\n\n## Checking Homogeneity of Variance (HoV)\n\n### Method 1: Visual Inspection of Variance Equality\n\n#### Equal Variances across groups\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = group, y = score)) +\n  geom_boxplot() +\n  theme_minimal() +\n  labs(title = \"Equal Variance: Boxplot of Scores by Group\", x = \"Group\", y = \"Score\")\n```\n\n::: {.cell-output-display}\n![](ESRM64103_Lecture03_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n#### Unequal Variances across groups\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data_unequal, aes(x = group, y = score)) +\n  geom_boxplot() +\n  theme_minimal() +\n  labs(title = \"Unequal Variances: Boxplot of Scores by Group\", x = \"Group\", y = \"Score\")\n```\n\n::: {.cell-output-display}\n![](ESRM64103_Lecture03_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n### Method 2: Using Bartlett’s Test\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Equal group:\\n\")\nbartlett.test(score ~ group, data = data)\ncat(\"Unequal group:\\n\" )\nbartlett.test(score ~ group, data = data_unequal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEqual group:\n\n\tBartlett test of homogeneity of variances\n\ndata:  score by group\nBartlett's K-squared = 2.0115, df = 3, p-value = 0.57\n\nUnequal group:\n\n\tBartlett test of homogeneity of variances\n\ndata:  score by group\nBartlett's K-squared = 82.755, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Interpretation**:\n\n- **Equal variance data**: The Bartlett test is non-significant (p > 0.05), indicating we have no evidence against the null hypothesis. We can assume the groups have homogeneous variances.\n- **Unequal variance data**: The Bartlett test is significant (p < 0.05), indicating strong evidence that variances differ across groups. This violates the homogeneity of variance assumption, and we should consider using Welch's ANOVA or other robust alternatives.\n\n------------------------------------------------------------------------\n\n### Method 3: Using Levene’s Test\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(score ~ group, data = data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  3  0.1779 0.9107\n      36               \n```\n\n\n:::\n\n```{.r .cell-code}\nleveneTest(score ~ group, data = data_unequal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value  Pr(>F)  \ngroup  3  3.4749 0.02581 *\n      36                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Interpretation**:\n\n- **Equal variance data**: Levene's test shows p > 0.05, confirming homogeneity of variance across groups.\n- **Unequal variance data**: Levene's test shows p < 0.05, indicating significant differences in variances. This suggests the homogeneity assumption is violated and alternative methods should be considered.\n\n### When to use each test\n\n\n- Use Levene's Test (more frequently used) when:\n\n  - Data may not be normally distributed\n  - Dealing with outliers in the dataset\n  - Working with small sample sizes\n  - Conducting preliminary tests for ANOVA with non-normal data\n  - General robustness is prioritized over power\n  \n- Use Bartlett's Test when:\n\n  - Data is confirmed to be normally distributed\n  - No significant outliers are present\n  - Larger sample sizes are available\n  - Maximum statistical power is desired (under normality)\n  - Preliminary testing for parametric procedures with normal data\n\n## Post-hoc Analysis\n\n### Tukey Honest Significant Differences (HSD) Test\n\n-   **Purpose**: Conducts all possible pairwise comparisons between group means while controlling the family-wise error rate at the specified alpha level (typically 0.05).\n\n-   **Why it's needed**: Simple pairwise t-tests after a significant ANOVA inflate the Type I error rate. Tukey HSD adjusts for multiple comparisons to maintain the overall error rate.\n\n-   **How it works**: Creates confidence intervals for all pairwise mean differences using the studentized range distribution, which accounts for the number of groups being compared.\n\n-   **Interpretation**: If a confidence interval does not include zero, or if p adj < 0.05, the pair of groups differs significantly.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntukey_result <- TukeyHSD(anova_result)\nprint(tukey_result$group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  diff        lwr       upr        p adj\nG1-Control -0.08482175 -5.6158112  5.446168 0.9999741881\nG2-Control  6.24011176  0.7091223 11.771101 0.0218818550\nG3-Control  9.89123122  4.3602418 15.422221 0.0001491636\nG2-G1       6.32493351  0.7939441 11.855923 0.0197364909\nG3-G1       9.97605296  4.4450635 15.507042 0.0001317258\nG3-G2       3.65111946 -1.8798700  9.182109 0.3003394077\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Interpretation**: The Tukey HSD test provides pairwise comparisons between all groups while controlling for family-wise error rate. The output shows:\n\n- **diff**: The difference in means between each pair of groups\n- **lwr & upr**: The 95% confidence interval for the difference\n- **p adj**: The adjusted p-value for multiple comparisons\n\nPairs with p adj < 0.05 indicate statistically significant differences between those groups.\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(tukey_result)\n```\n\n::: {.cell-output-display}\n![](ESRM64103_Lecture03_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n## Interpreting Results\n\n### ANOVA Statistics\n\n```         \n           Df Sum Sq Mean Sq F value   Pr(>F)    \ngroup        3  724.1  241.37   11.45 2.04e-05 ***\nResiduals   36  759.2   21.09                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(dplyr)\ndata |> \n  group_by(group) |> \n  summarise(\n    Mean = mean(score),\n    SD = sd(score)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  group    Mean    SD\n  <chr>   <dbl> <dbl>\n1 Control  18.2  4.47\n2 G1       18.1  4.98\n3 G2       24.4  5.34\n4 G3       28.1  3.33\n```\n\n\n:::\n:::\n\n\n\n\n\n\n-   A one-way analysis of variance (ANOVA) was conducted to examine the effect of teaching method on students' test scores. The results indicated a statistically significant difference in test scores across the four groups, (F(3, 36) = 11.45, p < .001). Post-hoc comparisons using the Tukey HSD test revealed that the Interactive method (G3) (M = 28.06, SD = 3.33) resulted in significantly higher scores than the Traditional method (M = 18.17, SD = 4.47) with p < .001. However, no significant difference was found between G1 and the Control group (p = .99). These results suggest that certain teaching methods can significantly improve student performance compared to traditional approaches.\n\n## Real-world Applications of ANOVA\n\n-   Experimental designs in psychology.\n-   Clinical trials in medicine.\n-   Market research and A/B testing.\n-   Example case studies.\n\n## Using Weights in ANOVA\n\n-   In some cases, observations may have different levels of reliability or importance.\n-   Weighted ANOVA allows us to account for these differences by assigning weights.\n-   Example: A study where some groups have higher variance and should contribute less to the analysis.\n\n## Correct Approach to Sampling Weights\n\n### Basic Principle\n- **Inverse weighting**: Weight = 1 / (Selection probability)\n- Clusters with larger samples have higher selection probabilities\n- Therefore, they receive smaller weights\n\n### Example\n- If Cluster A has 1000 people and you sampled 100, selection probability = 100/1000 = 0.1\n- If Cluster B has 100 people and you sampled 50, selection probability = 50/100 = 0.5\n- Weight for Cluster A = 1/0.1 = 10\n- Weight for Cluster B = 1/0.5 = 2\n\n### Why This Works\n- Oversampled groups (higher sampling fraction) get downweighted\n- Undersampled groups (lower sampling fraction) get upweighted\n- This corrects the disproportionate representation in your sample\n\n## Example: Applying Weights in `aov()`\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweights <- c(rep(1, 10), rep(2, 10), rep(0.5, 10), rep(1.5, 10))\nanova_weighted <- aov(score ~ group, data = data, weights = weights)\nsummary(anova_weighted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \ngroup        3  666.6  222.20   7.578 0.000471 ***\nResiduals   36 1055.5   29.32                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Interpretation**:\n\n-   The weights modify the influence of each observation in the model. In this example, G2 observations receive double weight (2.0), G3 observations receive half weight (0.5), and G1 and Control receive standard weights.\n-   Notice how the F-statistic and p-value change compared to the unweighted analysis, reflecting the differential contribution of each group.\n-   This approach is useful when data reliability varies across groups or when correcting for sampling design effects.\n\n## Where Do We Get Weights for ANOVA?\n\n-   Weights can be derived from:\n    -   **Large-scale assessments**: Different student groups may have varying reliability in measurement.\n    -   **Survey data**: Unequal probability of selection can be adjusted using weights.\n    -   **Experimental data**: Measurement error models may dictate different weight assignments.\n\n## Example: Using Weights in Large-Scale Assessments\n\n-   Consider an educational study where test scores are collected from schools of varying sizes.\n-   Larger schools may contribute more observations but should not dominate the analysis.\n-   Weighting adjusts for this imbalance:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweights <- ifelse(data$group == \"LargeSchool\", 0.5, 1)\nanova_weighted <- aov(score ~ group, data = data, weights = weights)\nsummary(anova_weighted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \ngroup        3  724.1  241.37   11.45 2.04e-05 ***\nResiduals   36  759.2   21.09                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Interpretation**:\n\n-   In this example, we apply conditional weighting where observations from \"LargeSchool\" receive half the weight (0.5) compared to other groups (weight = 1).\n-   This prevents larger schools from dominating the analysis due to their overrepresentation in the sample.\n-   The weighted analysis ensures fair representation across schools of different sizes, providing more generalizable results.\n\n## Conclusion and Interpretation\n\n-   Review results and discuss findings.\n-   Key takeaways from the analysis.\n\n\n",
    "supporting": [
      "ESRM64103_Lecture03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}