{
  "hash": "ea1ae57695e3af5da75ba11eab088951",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 08: Block Design (2)\"\nsubtitle: \"Experimental Design in Education\"\ndate: \"2025-03-07\"\ndate-modified: \"2025-03-08\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n\n\n\n::: objectives\n## Overview {.unnumbered}\n\n1.  Review Block Design\n2.  Randomized Block Design with R Programming[^1]\n3.  Completely Randomized Block Design with R Programming[^2]\n:::\n\n[^1]: Please check [here](https://www.geeksforgeeks.org/randomized-block-design-with-r-programming/) for the original post\n\n[^2]: Please check [here](https://www.geeksforgeeks.org/completely-randomized-design-with-r-programming/?ref=ml_lbp) for the original post\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Experiment 1\n\n-   **Background**: Testing new fertilizers in different types of crops.\n-   **Design**: Crops are divided into 3 different types (blocks). These blocks are again divided into 3 fertilizers (F1, F2, and NF) that are used on those crops. The figure of study design can be visualized as follows:\n\n![](https://media.geeksforgeeks.org/wp-content/uploads/20201014082316/RCBDexample.PNG)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorn <- factor(rep(c(\"corn\", \"rice\", \"wheat\"), each = 3)) \nfert <- factor(rep(c(\"f1\", \"f2\", \"nf\"), times = 3)) \ncorn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] corn  corn  corn  rice  rice  rice  wheat wheat wheat\nLevels: corn rice wheat\n```\n\n\n:::\n\n```{.r .cell-code}\nfert\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] f1 f2 nf f1 f2 nf f1 f2 nf\nLevels: f1 f2 nf\n```\n\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(6, 5, 6, \n       4, 4.2, 5, \n       5, 4.4, 5.5) \n\n# y is the months the crops were healthy \nresults <- data.frame(y, corn, fert) \ngt(results)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"btdqvloikh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#btdqvloikh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#btdqvloikh thead, #btdqvloikh tbody, #btdqvloikh tfoot, #btdqvloikh tr, #btdqvloikh td, #btdqvloikh th {\n  border-style: none;\n}\n\n#btdqvloikh p {\n  margin: 0;\n  padding: 0;\n}\n\n#btdqvloikh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#btdqvloikh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#btdqvloikh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#btdqvloikh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#btdqvloikh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#btdqvloikh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#btdqvloikh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#btdqvloikh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#btdqvloikh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#btdqvloikh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#btdqvloikh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#btdqvloikh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#btdqvloikh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#btdqvloikh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#btdqvloikh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#btdqvloikh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#btdqvloikh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#btdqvloikh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#btdqvloikh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#btdqvloikh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#btdqvloikh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#btdqvloikh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#btdqvloikh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#btdqvloikh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#btdqvloikh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#btdqvloikh .gt_left {\n  text-align: left;\n}\n\n#btdqvloikh .gt_center {\n  text-align: center;\n}\n\n#btdqvloikh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#btdqvloikh .gt_font_normal {\n  font-weight: normal;\n}\n\n#btdqvloikh .gt_font_bold {\n  font-weight: bold;\n}\n\n#btdqvloikh .gt_font_italic {\n  font-style: italic;\n}\n\n#btdqvloikh .gt_super {\n  font-size: 65%;\n}\n\n#btdqvloikh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#btdqvloikh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#btdqvloikh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#btdqvloikh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#btdqvloikh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#btdqvloikh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#btdqvloikh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#btdqvloikh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#btdqvloikh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"y\">y</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"corn\">corn</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"fert\">fert</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">6.0</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">corn</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">f1</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">5.0</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">corn</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">f2</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">6.0</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">corn</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">nf</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">4.0</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">rice</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">f1</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">4.2</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">rice</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">f2</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">5.0</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">rice</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">nf</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">5.0</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">wheat</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">f1</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">4.4</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">wheat</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">f2</td></tr>\n    <tr><td headers=\"y\" class=\"gt_row gt_right\">5.5</td>\n<td headers=\"corn\" class=\"gt_row gt_center\">wheat</td>\n<td headers=\"fert\" class=\"gt_row gt_center\">nf</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n------------------------------------------------------------------------\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- aov(y ~ fert+corn, data = results)\t\t\t\t \nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \nfert         2 1.4022  0.7011   6.505 0.0553 .\ncorn         2 2.4156  1.2078  11.206 0.0229 *\nResiduals    4 0.4311  0.1078                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n\n-   **Explanation:** The value of *Mean Sq* shows is blocking really necessary for the experiment. Here *Mean Sq for residuals* `0.1078 << 0.7011`, thus blocking is necessary will give precise values for the experiment. Though this method is a little debatable yet useful. The significance value of every experiment is given by the person taking the experiment. Here lets consider significance has 5% i.e 0.05. The Pr(\\>F) value is `0.0553>0.05`. Thus the hypothesis is accepted for the crops experiment. Let’s consider one more experiment.\n\n## Experiment 2\n\n-   **Background:** Comparing the performances of students (male and female) blocks in different environments (at home and at college). To represent this experiment in the figure will be as follows:\n\n![](https://media.geeksforgeeks.org/wp-content/uploads/20201015122147/RCBDexample2.PNG)\n\n-   Where *AC*: At College, *AH*: At Home\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstud <- factor(rep(c(\"male\", \"female\"), each = 2)) \nperf <- factor(rep(c(\"ah\", \"ac\" ), times = 2)) \nperf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] ah ac ah ac\nLevels: ac ah\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(5.5, 5, \n\t4, 6.2) \n\n# y is the hours students \n# studied in specific places \nresults <- data.frame(y, stud, perf) \n\nfit <- aov(y ~ perf+stud, data = results)\t\t\t\t \nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nperf         1 0.7225  0.7225   0.396  0.642\nstud         1 0.0225  0.0225   0.012  0.930\nResiduals    1 1.8225  1.8225               \n```\n\n\n:::\n:::\n\n\n\n\n\n\n-   **Explanation**: The value of Mean Sq is `0.7225<<1.8225`,i.e, here blocking wasn’t necessary. And as Pr value is 0.642 \\> 0.05 (5% significance) and the hypothesis is accepted - there is no sufficient evidence suggesting females and males have significant differences in performance.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}