---
title: "Note: Docker in Action, Second Edition"
subtitle: ""
description: ''
author: 'Jihong Zhang'
date: '2025-05-02'
sidebar: false
categories:
  - Docker
execute: 
  eval: false
  echo: true
  warning: false
  error: true
format: 
  html: 
    code-fold: false
    code-summary: 'Click to see the code'
    number-sections: true
---

# Chapter 1 - Welcome to Docker

> “Docker is a tool that makes adopting software packaging, distribution, and utilization best practices cheap and sensible defaults.”

Docker provides an expressive language that can:

-   inject environment-specific configuration
-   control access to system resources
-   built-in package management, tooling, and distribution infrastructure

## What is docker?

Docker was launched in March 2013. It is an open-source Linux software for building, shipping, and running programs.

```bash
docker run dockerinaction/hello_world
```

`docker run` command tells Docker to trigger the sequence. In the command, `dockerinaction/hello_world` is a Docker *image*.

Docker runs *containers.* Containers are running inside virtual machines for Mac, Windows, and other OS.

Docker uses Linux *namespaces* and *cgroups*.

Following command can display information about the basic syntax.

```bash
docker help
```

For specific command,

```bash
docker help cp
```

show how to copy files from a location inside a container to a location on the host machine.
