{
  "hash": "9a84910fea6166559b6ab4a303b8a1b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 08: Block Design II\"\nsubtitle: \"Experimental Design in Education\"\ndate: \"2025-03-07\"\ndate-modified: \"2025-10-15\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  message: false\nformat: \n  html:\n    code-tools: true\n    code-line-numbers: false\n    code-fold: false\n    code-summary: \"Click to see R code\"\n    number-offset: 1\n    fig.width: 10\n    fig-align: center\n    message: false\n    grid:\n      sidebar-width: 350px\n  uark-revealjs:\n    chalkboard: true\n    embed-resources: false\n    code-fold: false\n    number-sections: true\n    number-depth: 1\n    footer: \"ESRM 64503\"\n    slide-number: c/t\n    tbl-colwidths: auto\n    scrollable: true\n    output-file: slides-index.html\n    mermaid:\n      theme: forest    \nfilters:\n  - webr            \n---\n\n::: objectives\n## Overview {.unnumbered}\n\n1.  Review Last week's Lecture\n2.  Review Block Design\n3.  Randomized Complete Block Design with R Programming\n4.  [Homework 2 Link](https://docs.google.com/forms/d/e/1FAIpQLSfXv9fBlRLaGB5eV79qfL30AVOiul7bSrMWbqns2iCz7IdgHA/viewform?usp=header)\n:::\n\n\n\n## In last week (1)\n\n1.  We reviewed different types of randomized experiment design:\n    -   Block Design: Complete block design (CBD) vs. Randomized Complete Block Design (RCBD)\n        -   **Difference**: [A \"complete block design\" simply refers to an experimental design where every treatment is applied to every block, while a \"randomized complete block design\" takes that same concept and adds the element of randomly assigning treatments within each block]{.mohu}\n    -   Block Design with more block factors: Latin square design, Repeated LSD, Greco-Roman Squares\n        -   **Benefit**: [(1) Account for more explained variances and leads to lower residual variances; (2) Make the effect size of treatment more accurate;]{.mohu}\n        -   **Limitation**: [require block factors to have same number of levels.]{.mohu}\n\n## In last week (2)\n\n2.  We discussed about why we need Block design compared to using simple treatment-control design.\n    -   [Potential confounding effects that can become nuisance factors]{.mohu}\n    -   [Heterogeneity of samples (variability across gender, schools, age groups)]{.mohu}\n    -   [Greater generalization of results]{.mohu}\n3.  Assumptions of Block Design\n    -   [Continuous outcome]{.mohu}\n    -   [Experimental units are randomly sampled]{.mohu}\n    -   [No interactions between treatment factor(s) and blocking factor(s)]{.mohu}\n    -   [Each block group's outcome is normally distributed]{.mohu}\n    -   [Each block group has \"equal\" or \"close\" variances in outcome]{.mohu}\n\n## Features of RCBD\n\n::: discussion\nThink about our example of the effects of teaching methods (M1, M2, M3, M4) and measurement forms (F1, F2, F3, F4) to math performance.\n:::\n\n1.  In **randomized complete block design (RCBD)**, each block size is the same and is equal to the number of treatments (i.e. factor levels or factor level combinations).\n    -   For those who using measurement form (same block), they will be randomly assigned to 4 teaching methods.\n2.  Each treatment will be randomly assigned to exactly one experimental unit (i.e., students) within every block.\n3.  The assignments of treatment levels (teaching methods) to the experimental units (students) have to be done within each block separately.\n\n## Random Effects of RCBD\n\n1.  It is important to mention that blocks are usually ($U_{\\rho_j}$, but not always) treated as random effects as they typically represent the population of all possible blocks.\n2.  In other words, the mean comparison among specific blocks is not of interest. The variability could be large or small depending on your context.\n3.  However, the variation between blocks must be incorporated into the model.\n\n## Exercises\n\n:::: discussion\n-   A poultry experiment was run to investigate the effect of **diet** and **antibiotics** on egg production. They evaluated 2 diets of interest and 2 specific antibiotics that are on the market. The feed and antibiotic were combined and used to fill the feeding trays in barns. They chose 3 poultry farms at random and randomly assigned the combinations of diet and antibiotic to 4 barns within each farm. Total egg production by the chickens was recorded after 4 weeks.\n    1.  What is the experimental design (hint: think about the randomization process)?\n    2.  Identify which factors are treatment and block.\n\n::: {.callout-note .mohu}\n## Answer\n\na.  [RCBD.]{.mohu}\nb.  [treatment: combination of Diet and Antibiotic; block: Farms.]{.mohu}\n:::\n::::\n\n## Other Aspects of the RCBD\n\n-   The RCBD utilizes an *additive model* (two-way ANOVA without interaction)\n\n    -   one in which there is *no interaction* between treatments and blocks. The error term in a randomized complete block model reflects how the treatment effect varies from one block to another.\n\n-   Both the treatments and blocks can be considered as *random effects* rather than fixed effects, if the levels were selected at random from a population of possible treatments or blocks. We consider this case later, but it does not change the test for a treatment effect.\n\n-   What are the consequences of not blocking if we should have? Generally the **unexplained error** in the model will be larger, and therefore the test of the treatment effect less powerful.\n\n-   How to determine the sample size in the RCBD?\n\n    -   The [Operating Characteristic (OC) curve](https://online.stat.psu.edu/stat503/lesson/3/3.2#paragraph--298) approach can be used to determine the number of blocks to run. The number of blocks, *b*, represents the number of replications (they are exchangable from the point of researchers' view). The power calculations that we looked at before would be the same, except that we use b rather than n, and we use the estimate of error, $\\sigma^2$, that reflects the improved precision based on having used blocks in our experiment. So, the major benefit or power comes not from the number of replications but from the error variance which is much smaller because you removed the effects due to block.\n\n## Statistical form of RCBD\n\n-   The mean comparison among specific blocks ($\\mu_{form1}$, $\\mu_{form2}$, $\\mu_{form3}$, $\\mu_{form4}$) is not of interest\n    -   In a RCBD, the variation between blocks is partitioned out of the MSE, resulting in a smaller MSE for testing hypotheses about the treatments.\n\n$$\nY_{ij} = \\mu + \\tau_i + \\rho_j + \\epsilon_{ij}\n$$\n\nwhere:\n\n1.  $Y_{ij}$: math scores for Method *i* and Form *j*\n2.  $\\mu$: grand mean\n3.  $\\tau_i$: Method *i* with *i* = 1, ..., 4\n4.  $\\rho_j$: From *j* with *j* = 1, 2, 3\n5.  $\\rho_j$ and $\\epsilon_{ij}$ are independent random variables such that $\\rho_j \\sim \\mathcal{N}(0, \\sigma^2_{\\rho})$ and $\\epsilon_{ij} \\sim \\mathcal{N}(0, \\sigma^2_{\\epsilon})$\n\n## A little bit statistics [^1]\n\n[^1]: Original post can be found [here](https://www.stat.purdue.edu/~xbw/courses/stat514/notes/lec6.blockdesign.pdf)\n\n-   $\\bar{y}_{. .}$: the grand mean across all factor levels. $y_{i j}$: the observed outcome for each individual.\n\n-   $\\bar{y}_{i .}$: marginal means of treatment groups; $\\bar{y}_{j .}$: marginal means of blocks\n\n-   We can partition the total sum of squares of outcome Y: $\\mathrm{SS}_{\\mathrm{T}}=\\sum \\sum\\left(y_{i j}-\\bar{y}_{. .}\\right)^{2}$ into:\n\n$$\n\\mathrm{SS}_{\\mathrm{T}}= n_b \\sum\\left(\\bar{y}_{i .}-\\bar{y}_{. .}\\right)^{2}+ n_a \\sum\\left(\\bar{y}_{. j}-\\bar{y}_{. .}\\right)^{2}+\\sum \\sum\\left(y_{i j}-\\bar{y}_{i .}-\\bar{y}_{. j}+\\bar{y}_{. .}\\right)^{2}\n$$\n\n-   $\\mathrm{SS}_{\\mathrm{treatment}}= n_b \\sum\\left(\\bar{y}_{i .}-\\bar{y}_{. .}\\right)^{2}$ with $\\mathrm{df} = a -1$\n\n-   $\\mathrm{SS}_{\\mathrm{block}}= n_a \\sum\\left(\\bar{y}_{. j}-\\bar{y}_{. .}\\right)^{2}$ with $\\mathrm{df} = b -1$\n\n-   $\\mathrm{SS}_{\\mathrm{Residual}}= \\sum \\sum\\left(y_{i j}-\\bar{y}_{i .}-\\bar{y}_{. j}+\\bar{y}_{. .}\\right)^{2}$ with $\\mathrm{df} = (n_a-1)(n_b -1)$\n\n$$\n\\mathrm{SS}_{\\mathrm{T}} = \\mathrm{SS}_{\\mathrm{treatment}} + \\mathrm{SS}_{\\mathrm{block}} + \\mathrm{SS}_{\\mathrm{Residual}}\n$$\n\n## A little bit more statistics\n\n-   Assume treatment factor has $n_a$ levels and blocking factor has $n_b$ levels:\n\n$$\nSS_{Total}\n= \\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}(y_{ij})^2-(\\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}y_{ij})^2/N \n$$\n\n-   *Mean of \"sum of square\" of marginal sums* minus the mean of \"square of sum\"\n    -   Marginal Sums of treatment: $y_{i.}$\n\n$$\nSS_{Treatment}\n= \\frac{1}{n_b}\\sum{(y_{i.})}^2  -(\\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}y_{ij})^2/N \n$$\n\n-   *Mean of \"sum of square\" of marginal sums* minus the mean of \"square of sum\"\n    -   Marginal Sums of block: $y_{.j}$\n\n$$\nSS_{Block}\n= \\frac{1}{n_a}\\sum{(y_{.j})}^2  -(\\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}y_{ij})^2/N \n$$\n\n## Example 1: Performance of detergents\n\n::: callout-important\n### Background\n\nAn experiment was designed to study the performance of four different detergents in cleaning clothes. The following “cleanness” readings (higher=cleaner) were obtained with specially designed equipment for three different types of common stains. Is there a difference between the detergents?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(tidyverse)\ndetergents <- tribble(\n  ~Detergent, ~Stain1, ~Stain2, ~Stain3,\n  1, 45, 43, 51,\n  2, 47, 46, 52,\n  3, 48, 50, 55,\n  4, 42, 37, 49\n)\n```\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Detergent| Stain1| Stain2| Stain3|\n|---------:|------:|------:|------:|\n|         1|     45|     43|     51|\n|         2|     47|     46|     52|\n|         3|     48|     50|     55|\n|         4|     42|     37|     49|\n\n\n:::\n:::\n\n\n-   Marginal Sums of treatment: $y_{i.}$; R code: `rowSums(detergents[, 2:4])`\n\n-   Marginal Sums of Stain: $y_{.j}$; R code: `colSums(detergents[, 2:4])`\n\n------------------------------------------------------------------------\n\n### Statistics: Total Sum of Square\n\n1.  *Sum of square* of all values: $(\\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}y_{ij})^2$ = 26867\n2.  *Square of sum* of all values per level: $\\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}(y_{ij})^2$ = 26602\\.0833333333\n3.  **Total Sum of Squares**: $SS_{Total}$ = 264\\.916666666668\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsum((detergents[, 2:4])^2) - (sum(detergents[, 2:4]))^2 / 12\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 264.9167\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Statistics: Sum of squares for treatment groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreatment_marginal_Sums = rowSums(detergents[, 2:4])\ngrand_mean <- mean(unlist(detergents[, 2:4]))\n## Method 1\n3 * sum((treatment_marginal_Sums/3 - grand_mean)^2)\n## Method 2\nsum(treatment_marginal_Sums^2) / 3 - (sum(detergents[, 2:4]))^2 / 12\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 110.9167\n[1] 110.9167\n```\n\n\n:::\n:::\n\n\n1.  *Sum of square* per level: $\\frac{1}{n_b}\\sum{(y_{i.})}^2$ = 26713\n2.  *Square of sum* of all values: $\\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}(y_{ij})^2$ = 319225\n3.  **Sum of Squares for treatment**: $SS_{treatment}$ = 110\\.917\n\n------------------------------------------------------------------------\n\n### Statistics: Sum of squares for block groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblock_marginal_Sums = colSums(detergents[, 2:4])\n## Method 1\n4 * sum((block_marginal_Sums/4 - grand_mean)^2)\n## Method 2\n(1 / 4) * sum(block_marginal_Sums^2) - (sum(detergents[, 2:4]))^2 / 12\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 135.1667\n[1] 135.1667\n```\n\n\n:::\n:::\n\n\n1.  *Sum of square* per level: $\\frac{1}{n_b}\\sum{(y_{i.})}^2$ = 26737\\.25\n2.  *Square of sum* of all values: $\\sum_{i=1}^{n_a}\\sum_{j=1}^{n_b}(y_{ij})^2$ = 26602\\.0833333333\n3.  **Sum of Squares for block**: $SS_{block}$ = 135\\.166666666668\n\n## Results: F-statistics\n\n$$\nF = \\frac{SS_{\\mathrm{treatment}}/n_a}{SS_\\mathrm{residual}/ ((n_a-1)*(n_b-1))}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSS_total <- sum((detergents[, 2:4])^2) - (sum(detergents[, 2:4]))^2 / 12\nSS_treatment <- 3 * sum((treatment_marginal_Sums/3 - grand_mean)^2)\nSS_block <- 4 * sum((block_marginal_Sums/4 - grand_mean)^2)\nSS_residual = SS_total - SS_treatment - SS_block\ncat(\"Sum of square of residual errors:\\n\")\nSS_residual\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSum of square of residual errors:\n[1] 18.83333\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_stat = (SS_treatment / (4-1)) / (SS_residual / ((4-1)*(3-1)))\nF_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.77876\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### R Code using aov function\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetergents_aov <- detergents |> \n  pivot_longer(starts_with(\"Stain\"), names_to = \"Stain\") |>\n  mutate(Detergent = factor(Detergent, levels = 1:4))\n\nfit <- aov(value ~ Detergent+Stain, data= detergents_aov)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nDetergent    3 110.92   36.97   11.78 0.00631 **\nStain        2 135.17   67.58   21.53 0.00183 **\nResiduals    6  18.83    3.14                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nInterpretation: Detergents have significant differences, and the Stain type was a useful blocking factor.\n\n## Example 2: Tutoring session\n\n:::::: columns\n::: {.column width=\"60%\"}\n-   Let’s look at a simple example:\n-   Research question: **What is the effect of time of day (morning session vs. afternoon session) of tutoring session on midterm grades?**\n-   The Primary Investigator (PI) of the study wants to control for different tutor(s), believing some tutors may be better than others. Thus, they design a completely randomized block design.\n-   Each tutor works with students in the morning and afternoon.\n    -   In this example, student select their favorite tutor, but are then randomly assigned to either a morning (AM) or afternoon (PM) session.\n    -   200 total students: 91 in the morning, 109 in the afternoon\n:::\n\n:::: {.column width=\"40%\"}\n![](images/clipboard-3708810514.png)\n\n::: callout-note\nDV: Midterm Score (in cells)\n:::\n::::\n::::::\n\n------------------------------------------------------------------------\n\n### Variables and Null Hypothesis\n\n:::::: columns\n::: {.column width=\"60%\"}\n-   IV: Time (*a* = 2 )\n    -   [2 levels]{style=\"color: orange\"}: AM and PM\n-   Nuisance factor: Tutor (*b* = 4 )\n    -   [4 levels]{style=\"color: purple\"}: Booby, Julia, Monique, and Ned\n-   DV: Midterm Score\n-   Null hypothesis pertaining to the IV of interest:\n    -   $H_0:\\mu_{𝐴𝑀} = \\mu_{𝑃𝑀} → a= 2$\n-   We will also have a null hypothesis pertaining to the blocking factor:\n    -   $H_0:\\mu_{Bobby} = \\mu_{Julia} = \\mu_{Monique} =\\mu_{Ned} → b=4$\n-   Two Nulls = two values of $F_{obs}$, two values of $F_{crit}$, two decisions\n:::\n\n:::: {.column width=\"40%\"}\n![](images/clipboard-3708810514.png)\n\n::: callout-note\nDV: Midterm Score (in cells)\n:::\n::::\n::::::\n\n------------------------------------------------------------------------\n\n### Sum of Squares\n\n::::: columns\n::: {.column width=\"70%\"}\n-   IV: Time (𝑎= 2 )\n\n-   Nuisance factor: Tutor (𝑏= 4 )\n\n-   DV: Midterm Score\n\n-   Now:\n\n    -   $𝑆𝑆_{Total} =\\color{red}{𝑆𝑆_{𝑀𝑜𝑑𝑒𝑙}}+\\color{purple}{𝑆𝑆_{𝐵𝑙𝑜𝑐𝑘}}+\\color{blue}{𝑆𝑆_{𝐸𝑟𝑟𝑜𝑟}}$\n\n-   Thus, we can partition the effects into three parts:\n\n    -   Sum of squares due to [treatments (IV = Time)]{style=\"color: red\"},\n\n    -   Sum of squares due to the [blocking factor]{style=\"color: purple\"},\n\n    -   and Sum of squares due to [error]{style=\"color: blue\"}.\n\n-   We **do not** model an **interaction** with blocked designs. (we will talk about it later.)\n:::\n\n::: {.column width=\"30%\"}\n![](images/clipboard-624916915.png)\n:::\n:::::\n\n------------------------------------------------------------------------\n\n### Mean of Squares and F-statistics\n\n-   IV: Time (𝑎= 2 )\n-   Nuisance factor: Tutor (𝑏= 4 )\n-   DV: Midterm Score\n-   Model: $𝑆𝑆_{Total} =\\color{red}{𝑆𝑆_{𝑀𝑜𝑑𝑒𝑙}}+\\color{purple}{𝑆𝑆_{𝐵𝑙𝑜𝑐𝑘}}+\\color{blue}{𝑆𝑆_{𝐸𝑟𝑟𝑜𝑟}}$\n-   ANOVA table:\n\n![](images/clipboard-505786804.png)\n\n------------------------------------------------------------------------\n\n### Sum of Square Formula\n\n$$\nSS_{\\mathrm{Total}}=\\sum_{i=1}^{n}(y_{ij}-\\bar{y}_{..})^2\n$$\n\n-   This is the same as before: take each individual score ($y_{ij}$), subtract the grand mean ($\\bar{y}_{..}$), and square it $(y_{ij}-\\bar{y}_{..})^2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscores <- c(9.1, 9.3, 9.4, 9.5) # four individuals' scores\nmean(scores) # grand mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.325\n```\n\n\n:::\n\n```{.r .cell-code}\nsum((scores - mean(scores))^2) # sum of squares of total indivisuals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0875\n```\n\n\n:::\n:::\n\n\n-   Do this for everyone and then sum over all people $\\sum_{i=1}^{n}(y_{ij}-\\bar{y}_{..})^2$\n\n-   However, when calculating **S**um of **S**quares for IVs: $SS_{Model}$, $SS_{Block}$, $SS_{error}$, we need to compute \"**marginal means**\"\n\n    -   A **marginal mean** is the mean for one level of the variable, ignoring the other variable\n\n------------------------------------------------------------------------\n\n### Marginal Means\n\n-   A **marginal mean** is the mean for one level of the variable, ignoring the other variable\n\n::::: columns\n::: {.column width=\"50%\"}\n**For example**:\n\n-   The AM marginal mean is the average of all students’ midterm scores in the morning, ignoring who they have as a tutor $$\n    \\bar{y}_{AM.} = 22.95\n    $$\n-   The Bobby marginal mean is the average of all students’ midterm scores who had Bobby as a tutor, ignoring time of day $$\n    \\bar{y}_{.Bobby} = 11.91\n    $$\n:::\n\n::: {.column width=\"50%\"}\n![](images/clipboard-560146152.png)\n:::\n:::::\n\n------------------------------------------------------------------------\n\n### SS for Total and Time/Model\n\n$$\nSS_{Total} = \\sum_{i=1}^{n}(y_{ij}-\\bar{y}_{..})^2=15060.48\n$$\n\n$$\nSS_{Model(time)} = \\sum_{a=1}^{a}n_a(\\bar{y}_{a.}-\\bar{y}_{..})^2=4489.02\n$$\n\n-   where $n_a$ is the group size for AM/PM and $\\bar{y}_{a.}$ are the marginal means for AM and PM {22.95, 13.43}\n\n-   This is similar to how we computed $𝑆𝑆_{𝑀𝑜𝑑𝑒𝑙}$ before: marginal group mean subtract off the grand mean and square it. Sum over all groups.\n\n$$\nSS_{Block} = \\sum_{b=1}^{b}n_{b}(\\bar{y}_{.b}-\\bar{y}_{..})^2=3239.43\n$$\n\n-   Technically, the blocking factor is just another IV (but we are not interested in or is not within the scope of research question).\n\n    -   $𝑆𝑆_{𝐸𝑟𝑟𝑜𝑟} = 𝑆𝑆_{𝑇𝑜𝑡𝑎𝑙}− 𝑆𝑆_{𝑀𝑜𝑑𝑒𝑙} +𝑆𝑆_{𝐵𝑙𝑜𝑐𝑘}$ = 7332. 03\n\n------------------------------------------------------------------------\n\n### Results of ANOVA Table\n\n-   Then, we can fill out the ANOVA table:\n\n![](images/clipboard-122981133.png)\n\n::: callout-note\nUnder $\\alpha=.05$, for \"Model\" factor – Time, we have $df_{Model}$ = 1, $df_{error} = 195$: $F_{crit}=3.89$ so sig.\n\nSimilarly, for \"Blocking\" - Tutor, we have $df_{block}$ = 3, $df_{error} = 195$: $F_{crit}=2.65$ so sig.\n:::\n\n------------------------------------------------------------------------\n\n### Interpretation\n\n-   A randomized block design was used to test the effect of tutoring time on midterm scores. For each tutor, participants were randomly assigned to either morning (𝑛 = 91 ) or afternoon (𝑛= 109 ) tutoring sessions.\n-   The effect of tutoring time was significant $(𝐹(1,195) = 119. 39, 𝑝<. 001 ,\\eta^2_{𝑇𝑖𝑚𝑒} =. 298$) with a large effect. Using a Tukey’s test, morning is significantly higher than afternoon sessions (𝑝 \\<. 05 ).\n-   The effect of the blocking factor, tutor, was significant ($𝐹(3 , 195) = 28. 72 ,𝑝< . 001 ,\\eta^2_{𝑇𝑢𝑡𝑜𝑟} =. 215$) with a large effect. Using a Tukey’s test, Monique’s students were significantly higher than other students, and Bobby’s students were significantly lower than other students in the midterm scores (𝑝\\<. 05 ).\n\n## Example 3: Hardness Reading[^2]\n\n[^2]: Please check the original post here: [STAT 503](https://online.stat.psu.edu/stat503/lesson/4/4.1)\n\n-   In this example we wish to determine whether 4 different tips (the treatment factor) produce different (mean) hardness readings on a Rockwell hardness tester.\n    -   The **treatment factor** is the design of the tip for the machine that determines the hardness of metal. The tip is one component of the testing machine.\n\n::: callout-note\n### The Rockwell hardness test\n\n**The Rockwell hardness test** is a hardness test based on indentation hardness of a material. The Rockwell test measures the depth of penetration of an indenter under a large load (major load) compared to the penetration made by a preload (minor load).\n:::\n\n-   To conduct this experiment we assign the tips to an experimental unit; that is, to a **test specimen** (called a coupon), which is a piece of metal on which the tip is tested.\n    -   The **blocking factor** is the block of test specimens. The test specimens are blocks of metal that are similar in hardness. The test specimens are used to block the variation in hardness of the metal from the variation in the tips.\n\n------------------------------------------------------------------------\n\n### Example: Block Design - CRD\n\n-   If the structure were a completely randomized experiment (CRD) that we discussed in lecture 7, we would assign the tips to a random piece of metal for each test. In this case, the test specimens would be considered a source of nuisance variability.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1234)\ndata.frame(\n  Metal = paste0(\"Metal\", 1:8),\n  Tip = rep(c(\"Tip1\", \"Tip2\", \"Tip3\", \"Tip4\"), each = 2),\n  Hardness = sample(seq(9, 10, by =.1), 8)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Metal  Tip Hardness\n1 Metal1 Tip1      9.9\n2 Metal2 Tip1      9.5\n3 Metal3 Tip2      9.4\n4 Metal4 Tip2      9.3\n5 Metal5 Tip3      9.6\n6 Metal6 Tip3      9.0\n7 Metal7 Tip4      9.8\n8 Metal8 Tip4      9.1\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Example: Block Design - RCBD\n\n-   If we conduct this as a blocked experiment, we would assign all four tips to the same test specimen, randomly assigned to be tested on a different location on the specimen. Since each treatment occurs once in each block, the number of test specimens is the number of replicates.\n\n-   Back to the hardness testing example, the experimenter may very well want to *test the tips* (treatment) across *specimens* (block) of various hardness levels. This shows the importance of blocking. To conduct this experiment as a RCBD, we assign all 4 tips to each specimen.\n\n    -   In this experiment, each specimen is called a “block”; thus, we have designed a more homogenous set of experimental units on which to test the tips.\n\n------------------------------------------------------------------------\n\n### Example: Block Design Table - RCBD\n\n::::: columns\n::: column\n-   Suppose that we use b = 4 blocks as shown in the table below:\n\n-   We are primarily interested in testing the equality of treatment means, but now we have the ability to remove the variability associated with the nuisance factor (the blocks) through the grouping of the experimental units prior to having assigned the treatments.\n:::\n\n::: column\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntribble(\n  ~`1`, \t~`2`, \t~`3`, \t~`4`,\n  \"Tip 3\", \t\"Tip 3\", \t\"Tip 2\",\t\"Tip 1\",\n  \"Tip 1\", \t\"Tip 4\", \t\"Tip 1\",\t\"Tip 4\",\n  \"Tip 4\", \t\"Tip 2\", \t\"Tip 3\",\t\"Tip 3\",\n  \"Tip 2\", \t\"Tip 1\", \t\"Tip 4\",\t\"Tip 3\"\n) |> \n  gt() |> \n  tab_header(\n    title = \"The Hardness Testing Experiment\",\n    subtitle = \"Randomized Complete Block Design\"\n  ) |> \n  tab_spanner(\n    label = \"Test Coupon (Block)\",\n    columns = everything()\n  ) |> \n  tab_options(\n    table.width = px(500),\n    table.font.size = px(20)\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pdbgvzfont\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pdbgvzfont table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pdbgvzfont thead, #pdbgvzfont tbody, #pdbgvzfont tfoot, #pdbgvzfont tr, #pdbgvzfont td, #pdbgvzfont th {\n  border-style: none;\n}\n\n#pdbgvzfont p {\n  margin: 0;\n  padding: 0;\n}\n\n#pdbgvzfont .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 20px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 500px;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pdbgvzfont .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pdbgvzfont .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pdbgvzfont .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pdbgvzfont .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pdbgvzfont .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pdbgvzfont .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pdbgvzfont .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pdbgvzfont .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pdbgvzfont .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pdbgvzfont .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pdbgvzfont .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pdbgvzfont .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pdbgvzfont .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pdbgvzfont .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdbgvzfont .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pdbgvzfont .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pdbgvzfont .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pdbgvzfont .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdbgvzfont .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pdbgvzfont .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdbgvzfont .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pdbgvzfont .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdbgvzfont .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pdbgvzfont .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pdbgvzfont .gt_left {\n  text-align: left;\n}\n\n#pdbgvzfont .gt_center {\n  text-align: center;\n}\n\n#pdbgvzfont .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pdbgvzfont .gt_font_normal {\n  font-weight: normal;\n}\n\n#pdbgvzfont .gt_font_bold {\n  font-weight: bold;\n}\n\n#pdbgvzfont .gt_font_italic {\n  font-style: italic;\n}\n\n#pdbgvzfont .gt_super {\n  font-size: 65%;\n}\n\n#pdbgvzfont .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pdbgvzfont .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pdbgvzfont .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pdbgvzfont .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pdbgvzfont .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pdbgvzfont .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pdbgvzfont .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pdbgvzfont .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pdbgvzfont div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>The Hardness Testing Experiment</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Randomized Complete Block Design</td>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" scope=\"colgroup\" id=\"Test Coupon (Block)\">\n        <div class=\"gt_column_spanner\">Test Coupon (Block)</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a1\">1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a2\">2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a3\">3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a4\">4</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"1\" class=\"gt_row gt_left\">Tip 3</td>\n<td headers=\"2\" class=\"gt_row gt_left\">Tip 3</td>\n<td headers=\"3\" class=\"gt_row gt_left\">Tip 2</td>\n<td headers=\"4\" class=\"gt_row gt_left\">Tip 1</td></tr>\n    <tr><td headers=\"1\" class=\"gt_row gt_left\">Tip 1</td>\n<td headers=\"2\" class=\"gt_row gt_left\">Tip 4</td>\n<td headers=\"3\" class=\"gt_row gt_left\">Tip 1</td>\n<td headers=\"4\" class=\"gt_row gt_left\">Tip 4</td></tr>\n    <tr><td headers=\"1\" class=\"gt_row gt_left\">Tip 4</td>\n<td headers=\"2\" class=\"gt_row gt_left\">Tip 2</td>\n<td headers=\"3\" class=\"gt_row gt_left\">Tip 3</td>\n<td headers=\"4\" class=\"gt_row gt_left\">Tip 3</td></tr>\n    <tr><td headers=\"1\" class=\"gt_row gt_left\">Tip 2</td>\n<td headers=\"2\" class=\"gt_row gt_left\">Tip 1</td>\n<td headers=\"3\" class=\"gt_row gt_left\">Tip 4</td>\n<td headers=\"4\" class=\"gt_row gt_left\">Tip 3</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n:::::\n\n::: callout-important\nNotice the two-way structure of the experiment. Here we have four blocks and within each of these blocks is a random assignment of the tips within each block.\n:::\n\n------------------------------------------------------------------------\n\n### Example: ANOVA Results (1)\n\n-   Remember, the hardness of specimens (coupons) is tested with 4 different tips.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(here)\ndat <- read.csv(here::here(\"teaching/2025-01-13-Experiment-Design/Lecture08\", \"tip_hardness.csv\"))\nhead(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Obs Tip Hardness Coupon\n1   1   1      9.3      1\n2   2   1      9.4      2\n3   3   1      9.6      3\n4   4   1     10.0      4\n5   5   2      9.4      1\n6   6   2      9.3      2\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Example: ANOVA Results (2)\n\n-   Here is the output from R `aov()`. We can see four levels of the Tip and four levels for Coupon:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndat$Tip <- factor(dat$Tip)\ndat$Coupon <- factor(dat$Coupon)\nfit_exp2 <- aov(Hardness ~ Tip + Coupon, data = dat)\n```\n:::\n\n\n::: callout-note\n-   The Analysis of Variance table shows three degrees of freedom for Tip three for Coupon, and the residual (error) degrees of freedom is nine.\n\n-   The ratio of mean squares of treatment over error gives us an F ratio that is equal to 14.44 which is highly significant since it is greater than the .001 percentile of the F distribution with three and nine degrees of freedom.\n\n-   Our 2-way analysis also provides a test for the block factor, Coupon. The ANOVA shows that this factor is also significant with an F-test = 30.94. So, there is a large amount of variation in hardness between the pieces of metal.\n\n-   This is why we used specimen (or coupon) as our blocking factor. We expected in advance that it would account for a large amount of variation. By including block in the model and in the analysis, we removed this large portion of the variation, such that the residual error is quite small. By including a block factor in the model, the error variance is reduced, and the test on treatments is more powerful.\n:::\n\n### Example: ANOVA Results (3)\n\n-   The test on the block factor is typically not of interest except to confirm that you used a good blocking factor. The results are summarized by the table of means given below.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ncbind(\ndat |> \n  group_by(Tip) |>\n  summarize(\n    N_Tip = n(),\n    Hardness_Tip = mean(Hardness)),\ndat |> \n  group_by(Coupon) |>\n  summarize(\n    N_Coupon = n(),\n    Hardness_Coupon = mean(Hardness)) \n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tip N_Tip Hardness_Tip Coupon N_Coupon Hardness_Coupon\n1   1     4        9.575      1        4           9.400\n2   2     4        9.600      2        4           9.425\n3   3     4        9.450      3        4           9.725\n4   4     4        9.875      4        4           9.950\n```\n\n\n:::\n:::\n\n\n## Example 4: Plant Fertilizer[^3]\n\n[^3]: Please check the original post here: [STAT 502 Analysis of Variance and Design of Experiments](https://online.stat.psu.edu/stat502/lesson/7/7.3)\n\n::::: columns\n::: column\n1.  In a greenhouse experiment, there was a single factor (fertilizer) with 4 levels (i.e. 4 treatments), six replications, and a total of 24 experimental units (potted plants). Suppose the image below is the greenhouse bench (viewed from above) that was used for the experiment.\n\n2.  To use CBD, we need to randomly assign each of the treatment levels to 6 potted plants. To do this, we first assign numbers to the physical position of the pots on the bench. Each column of plants will be use one Fertilizer.\n\n3.  To further expand it to RCBD, we need to put them into different farms (say we have six farms). Each farms will have 4 plans with each will use one type of fertilizer.\n:::\n\n::: column\n![](images/clipboard-1929254708.png){width=\"100%\"}\n:::\n:::::\n\n------------------------------------------------------------------------\n\n### Read in R Data\n\n-   After saving the **exp1_data.csv** into the same directory of your R file. You should be able to import dataset from Files Panel in Rstudio:\n\n![](images/clipboard-1848460327.png)\n\n![](images/clipboard-1116098669.png)\n\n------------------------------------------------------------------------\n\n### Block Design\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt(dat, \n   rownames_to_stub = TRUE, \n   groupname_col = \"Block\", \n   row_group_as_column = TRUE) |> \n   tab_options(table.width = px(500))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nxdduhtxcd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nxdduhtxcd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nxdduhtxcd thead, #nxdduhtxcd tbody, #nxdduhtxcd tfoot, #nxdduhtxcd tr, #nxdduhtxcd td, #nxdduhtxcd th {\n  border-style: none;\n}\n\n#nxdduhtxcd p {\n  margin: 0;\n  padding: 0;\n}\n\n#nxdduhtxcd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 500px;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nxdduhtxcd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nxdduhtxcd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nxdduhtxcd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nxdduhtxcd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nxdduhtxcd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nxdduhtxcd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nxdduhtxcd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nxdduhtxcd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nxdduhtxcd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nxdduhtxcd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nxdduhtxcd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nxdduhtxcd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nxdduhtxcd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nxdduhtxcd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxdduhtxcd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nxdduhtxcd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nxdduhtxcd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nxdduhtxcd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxdduhtxcd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nxdduhtxcd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxdduhtxcd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nxdduhtxcd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxdduhtxcd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nxdduhtxcd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nxdduhtxcd .gt_left {\n  text-align: left;\n}\n\n#nxdduhtxcd .gt_center {\n  text-align: center;\n}\n\n#nxdduhtxcd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nxdduhtxcd .gt_font_normal {\n  font-weight: normal;\n}\n\n#nxdduhtxcd .gt_font_bold {\n  font-weight: bold;\n}\n\n#nxdduhtxcd .gt_font_italic {\n  font-style: italic;\n}\n\n#nxdduhtxcd .gt_super {\n  font-size: 65%;\n}\n\n#nxdduhtxcd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nxdduhtxcd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nxdduhtxcd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nxdduhtxcd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nxdduhtxcd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nxdduhtxcd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nxdduhtxcd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nxdduhtxcd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nxdduhtxcd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Fertilizer\">Fertilizer</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Height\">Height</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Plant\">Plant</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_row_group_first\"><td headers=\"Block1 stub_2_1 stub_1\" rowspan=\"4\" class=\"gt_row gt_left gt_stub_row_group\">Block1</td>\n<th id=\"stub_2_1\" scope=\"row\" class=\"gt_row gt_right gt_stub\">1</th>\n<td headers=\"Block1 stub_2_1 Fertilizer\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Block1 stub_2_1 Height\" class=\"gt_row gt_right\">19.5</td>\n<td headers=\"Block1 stub_2_1 Plant\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><th id=\"Fertilizer_2\" scope=\"row\" class=\"gt_row gt_right gt_stub\">7</th>\n<td headers=\"Block1 Fertilizer_2 Fertilizer\" class=\"gt_row gt_left\">F1</td>\n<td headers=\"Block1 Fertilizer_2 Height\" class=\"gt_row gt_right\">25.0</td>\n<td headers=\"Block1 Fertilizer_2 Plant\" class=\"gt_row gt_right\">7</td></tr>\n    <tr><th id=\"Fertilizer_3\" scope=\"row\" class=\"gt_row gt_right gt_stub\">13</th>\n<td headers=\"Block1 Fertilizer_3 Fertilizer\" class=\"gt_row gt_left\">F2</td>\n<td headers=\"Block1 Fertilizer_3 Height\" class=\"gt_row gt_right\">22.5</td>\n<td headers=\"Block1 Fertilizer_3 Plant\" class=\"gt_row gt_right\">13</td></tr>\n    <tr><th id=\"Fertilizer_4\" scope=\"row\" class=\"gt_row gt_right gt_stub\">19</th>\n<td headers=\"Block1 Fertilizer_4 Fertilizer\" class=\"gt_row gt_left\">F3</td>\n<td headers=\"Block1 Fertilizer_4 Height\" class=\"gt_row gt_right\">27.5</td>\n<td headers=\"Block1 Fertilizer_4 Plant\" class=\"gt_row gt_right\">19</td></tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Block2 stub_2_5 stub_1\" rowspan=\"4\" class=\"gt_row gt_left gt_stub_row_group\">Block2</td>\n<th id=\"stub_2_5\" scope=\"row\" class=\"gt_row gt_right gt_stub\">2</th>\n<td headers=\"Block2 stub_2_5 Fertilizer\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Block2 stub_2_5 Height\" class=\"gt_row gt_right\">20.5</td>\n<td headers=\"Block2 stub_2_5 Plant\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><th id=\"Fertilizer_6\" scope=\"row\" class=\"gt_row gt_right gt_stub\">8</th>\n<td headers=\"Block2 Fertilizer_6 Fertilizer\" class=\"gt_row gt_left\">F1</td>\n<td headers=\"Block2 Fertilizer_6 Height\" class=\"gt_row gt_right\">27.5</td>\n<td headers=\"Block2 Fertilizer_6 Plant\" class=\"gt_row gt_right\">8</td></tr>\n    <tr><th id=\"Fertilizer_7\" scope=\"row\" class=\"gt_row gt_right gt_stub\">14</th>\n<td headers=\"Block2 Fertilizer_7 Fertilizer\" class=\"gt_row gt_left\">F2</td>\n<td headers=\"Block2 Fertilizer_7 Height\" class=\"gt_row gt_right\">25.2</td>\n<td headers=\"Block2 Fertilizer_7 Plant\" class=\"gt_row gt_right\">14</td></tr>\n    <tr><th id=\"Fertilizer_8\" scope=\"row\" class=\"gt_row gt_right gt_stub\">20</th>\n<td headers=\"Block2 Fertilizer_8 Fertilizer\" class=\"gt_row gt_left\">F3</td>\n<td headers=\"Block2 Fertilizer_8 Height\" class=\"gt_row gt_right\">28.0</td>\n<td headers=\"Block2 Fertilizer_8 Plant\" class=\"gt_row gt_right\">20</td></tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Block3 stub_2_9 stub_1\" rowspan=\"4\" class=\"gt_row gt_left gt_stub_row_group\">Block3</td>\n<th id=\"stub_2_9\" scope=\"row\" class=\"gt_row gt_right gt_stub\">3</th>\n<td headers=\"Block3 stub_2_9 Fertilizer\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Block3 stub_2_9 Height\" class=\"gt_row gt_right\">21.0</td>\n<td headers=\"Block3 stub_2_9 Plant\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><th id=\"Fertilizer_10\" scope=\"row\" class=\"gt_row gt_right gt_stub\">9</th>\n<td headers=\"Block3 Fertilizer_10 Fertilizer\" class=\"gt_row gt_left\">F1</td>\n<td headers=\"Block3 Fertilizer_10 Height\" class=\"gt_row gt_right\">28.0</td>\n<td headers=\"Block3 Fertilizer_10 Plant\" class=\"gt_row gt_right\">9</td></tr>\n    <tr><th id=\"Fertilizer_11\" scope=\"row\" class=\"gt_row gt_right gt_stub\">15</th>\n<td headers=\"Block3 Fertilizer_11 Fertilizer\" class=\"gt_row gt_left\">F2</td>\n<td headers=\"Block3 Fertilizer_11 Height\" class=\"gt_row gt_right\">26.0</td>\n<td headers=\"Block3 Fertilizer_11 Plant\" class=\"gt_row gt_right\">15</td></tr>\n    <tr><th id=\"Fertilizer_12\" scope=\"row\" class=\"gt_row gt_right gt_stub\">21</th>\n<td headers=\"Block3 Fertilizer_12 Fertilizer\" class=\"gt_row gt_left\">F3</td>\n<td headers=\"Block3 Fertilizer_12 Height\" class=\"gt_row gt_right\">29.2</td>\n<td headers=\"Block3 Fertilizer_12 Plant\" class=\"gt_row gt_right\">21</td></tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Block4 stub_2_13 stub_1\" rowspan=\"4\" class=\"gt_row gt_left gt_stub_row_group\">Block4</td>\n<th id=\"stub_2_13\" scope=\"row\" class=\"gt_row gt_right gt_stub\">4</th>\n<td headers=\"Block4 stub_2_13 Fertilizer\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Block4 stub_2_13 Height\" class=\"gt_row gt_right\">21.0</td>\n<td headers=\"Block4 stub_2_13 Plant\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><th id=\"Fertilizer_14\" scope=\"row\" class=\"gt_row gt_right gt_stub\">10</th>\n<td headers=\"Block4 Fertilizer_14 Fertilizer\" class=\"gt_row gt_left\">F1</td>\n<td headers=\"Block4 Fertilizer_14 Height\" class=\"gt_row gt_right\">28.6</td>\n<td headers=\"Block4 Fertilizer_14 Plant\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><th id=\"Fertilizer_15\" scope=\"row\" class=\"gt_row gt_right gt_stub\">16</th>\n<td headers=\"Block4 Fertilizer_15 Fertilizer\" class=\"gt_row gt_left\">F2</td>\n<td headers=\"Block4 Fertilizer_15 Height\" class=\"gt_row gt_right\">26.5</td>\n<td headers=\"Block4 Fertilizer_15 Plant\" class=\"gt_row gt_right\">16</td></tr>\n    <tr><th id=\"Fertilizer_16\" scope=\"row\" class=\"gt_row gt_right gt_stub\">22</th>\n<td headers=\"Block4 Fertilizer_16 Fertilizer\" class=\"gt_row gt_left\">F3</td>\n<td headers=\"Block4 Fertilizer_16 Height\" class=\"gt_row gt_right\">29.5</td>\n<td headers=\"Block4 Fertilizer_16 Plant\" class=\"gt_row gt_right\">22</td></tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Block5 stub_2_17 stub_1\" rowspan=\"4\" class=\"gt_row gt_left gt_stub_row_group\">Block5</td>\n<th id=\"stub_2_17\" scope=\"row\" class=\"gt_row gt_right gt_stub\">5</th>\n<td headers=\"Block5 stub_2_17 Fertilizer\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Block5 stub_2_17 Height\" class=\"gt_row gt_right\">21.5</td>\n<td headers=\"Block5 stub_2_17 Plant\" class=\"gt_row gt_right\">5</td></tr>\n    <tr><th id=\"Fertilizer_18\" scope=\"row\" class=\"gt_row gt_right gt_stub\">11</th>\n<td headers=\"Block5 Fertilizer_18 Fertilizer\" class=\"gt_row gt_left\">F1</td>\n<td headers=\"Block5 Fertilizer_18 Height\" class=\"gt_row gt_right\">30.5</td>\n<td headers=\"Block5 Fertilizer_18 Plant\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><th id=\"Fertilizer_19\" scope=\"row\" class=\"gt_row gt_right gt_stub\">17</th>\n<td headers=\"Block5 Fertilizer_19 Fertilizer\" class=\"gt_row gt_left\">F2</td>\n<td headers=\"Block5 Fertilizer_19 Height\" class=\"gt_row gt_right\">27.0</td>\n<td headers=\"Block5 Fertilizer_19 Plant\" class=\"gt_row gt_right\">17</td></tr>\n    <tr><th id=\"Fertilizer_20\" scope=\"row\" class=\"gt_row gt_right gt_stub\">23</th>\n<td headers=\"Block5 Fertilizer_20 Fertilizer\" class=\"gt_row gt_left\">F3</td>\n<td headers=\"Block5 Fertilizer_20 Height\" class=\"gt_row gt_right\">30.0</td>\n<td headers=\"Block5 Fertilizer_20 Plant\" class=\"gt_row gt_right\">23</td></tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Block6 stub_2_21 stub_1\" rowspan=\"4\" class=\"gt_row gt_left gt_stub_row_group\">Block6</td>\n<th id=\"stub_2_21\" scope=\"row\" class=\"gt_row gt_right gt_stub\">6</th>\n<td headers=\"Block6 stub_2_21 Fertilizer\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Block6 stub_2_21 Height\" class=\"gt_row gt_right\">22.5</td>\n<td headers=\"Block6 stub_2_21 Plant\" class=\"gt_row gt_right\">6</td></tr>\n    <tr><th id=\"Fertilizer_22\" scope=\"row\" class=\"gt_row gt_right gt_stub\">12</th>\n<td headers=\"Block6 Fertilizer_22 Fertilizer\" class=\"gt_row gt_left\">F1</td>\n<td headers=\"Block6 Fertilizer_22 Height\" class=\"gt_row gt_right\">32.0</td>\n<td headers=\"Block6 Fertilizer_22 Plant\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><th id=\"Fertilizer_23\" scope=\"row\" class=\"gt_row gt_right gt_stub\">18</th>\n<td headers=\"Block6 Fertilizer_23 Fertilizer\" class=\"gt_row gt_left\">F2</td>\n<td headers=\"Block6 Fertilizer_23 Height\" class=\"gt_row gt_right\">28.0</td>\n<td headers=\"Block6 Fertilizer_23 Plant\" class=\"gt_row gt_right\">18</td></tr>\n    <tr><th id=\"Fertilizer_24\" scope=\"row\" class=\"gt_row gt_right gt_stub\">24</th>\n<td headers=\"Block6 Fertilizer_24 Fertilizer\" class=\"gt_row gt_left\">F3</td>\n<td headers=\"Block6 Fertilizer_24 Height\" class=\"gt_row gt_right\">31.0</td>\n<td headers=\"Block6 Fertilizer_24 Plant\" class=\"gt_row gt_right\">24</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### ANOVA Results\n\n:::::: columns\n::: column\n-   Let us obtain the ANOVA table for the **RCBD**. To run the model with Block Design in R we can use the `aov()` function with the formula:\n\n`<Outcome>~<Treatment>+<Block>`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_rcbd <- aov(Height ~ Fertilizer + Block, data = dat)\t\t\t\t \nsummary(fit_rcbd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nFertilizer   3 251.44   83.81  162.96 1.14e-11 ***\nBlock        5  53.32   10.66   20.73 2.99e-06 ***\nResiduals   15   7.71    0.51                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n::: column\n-   For comparison, let us obtain the ANOVA table for the **CRD** for the same data. We use the following R code with the formula:\n\n`<Outcome>~<Treatment>`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_cbd <- aov(Height ~ Fertilizer, data = dat)\t\t\t\t \nsummary(fit_cbd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nFertilizer   3 251.44   83.81   27.46 2.71e-07 ***\nResiduals   20  61.03    3.05                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n------------------------------------------------------------------------\n\n### Interpretation\n\n::: callout-important\nComparing the two ANOVA tables, we see that the MSE in RCBD has decreased considerably in comparison to the CRD. This reduction in MSE can be viewed as the partition in SSE for the CRD (61.033) into SSBlock (53.32) + SSE (7.715). The potential reduction in SSE by blocking is offset to some degree by losing degrees of freedom for the blocks. But more often than not, is worth it in terms of the improvement in the calculated *F*-statistic. In our example, we observe that the *F*-statistic for the treatment has increased considerably for RCBD in comparison to CRD. It is reasonable to assume that the result from the RCBD is more valid than that from the CRD as the MSE value obtained after accounting for the block to block variability is a more accurate representation of the random error variance.\n:::\n::::::\n\n## Example 5: Hours spent at varied environment\n\n-   **Background:** Comparing the hours spent on the study for gender (male and female) blocks in different environments (at home and at college). To represent this experiment in the figure will be as follows:\n\n![](https://media.geeksforgeeks.org/wp-content/uploads/20201015122147/RCBDexample2.PNG)\n\n-   Where *AC*: At College, *AH*: At Home\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngender <- factor(rep(c(\"male\", \"female\"), each = 2)) \nenv <- factor(rep(c(\"ah\", \"ac\" ), times = 2)) \ny <- c(5.5, 5, 4, 6.2) \n# y is the hours students \n# studied in specific places \nresults <- data.frame(y, gender, env) \nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    y gender env\n1 5.5   male  ah\n2 5.0   male  ac\n3 4.0 female  ah\n4 6.2 female  ac\n```\n\n\n:::\n:::\n\n::: panel-tabset\n### Exercise\n\nTry to obtain (1) the sum of squares for treatment and block (2) F-statistics. Then, interpret the results. \n\n```{webr-r}\ngender <- factor(rep(c(\"male\", \"female\"), each = 2)) \nenv <- factor(rep(c(\"ah\", \"ac\" ), times = 2)) \ny <- c(5.5, 5, 4, 6.2) \n# y is the hours students \n# studied in specific places \nresults <- data.frame(y, gender, env) \nresults\n```\n\n### Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- aov(y ~ gender+env, data = results)\t\t\t\t \nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\ngender       1 0.0225  0.0225   0.012  0.930\nenv          1 0.7225  0.7225   0.396  0.642\nResiduals    1 1.8225  1.8225               \n```\n\n\n:::\n:::\n\n\n-   **Explanation**: The value of Mean Sq is `0.7225<<1.8225`,i.e, here blocking wasn't necessary. And as Pr value is 0.642 \\> 0.05 (5% significance) we fail to reject the null hypothesis - there is no sufficient evidence suggesting females and males have significant differences in performance.\n:::\n\n## Blocking factor or not?\n\n::: discussion\n### Effectiveness of Health Promotion Programs {.unnumbered}\n\n-   Researchers are interested in comparing the effectiveness of three health promotion programs with nursing students.\n-   The researcher has the following research question: *Which of the three health promotion programs are most effective at reducing unhealthy coping behaviors?*\n    1.  Unhealthy coping behavior is measured as a composite score from the “Poor Coping Behavior” survey (PCB). High scores on the PCB indicate higher levels of unhealthy coping behaviors. Low scores indicate low levels of unhealthy coping behaviors. PCB scores can range from 0 (no unhealthy behaviors) to 100 (multiple unhealthy behaviors at high frequency and high intensity).\n    2.  The researcher thinks that the health promotion programs for nursing students may have an effect on academic and well-being outcomes.\n    3.  However, gender and status (traditional vs. non-traditional student) differences may influence the effectiveness of health promotion programs.\n:::\n\n------------------------------------------------------------------------\n\n### Blocking Factors?\n\n-   The researcher has a sample of 200 nursing students from the state of Arkansas. 50 students are assigned to each program: Program A, Program B, and Program C. In addition, 50 students are assigned to a control group that receives the status quo educational model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  Health_Program = c(\"Program A\", \"Program B\", \"Program C\", \"Control\"),\n  N = c(50, 50, 50, 50)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Health_Program  N\n1      Program A 50\n2      Program B 50\n3      Program C 50\n4        Control 50\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Blocking Factors?\n\n::: panel-tabset\n## Visualization\n\n![](images/clipboard-1200507560.png)\n\n## Table\n\n![](images/clipboard-2055304403.png)\n:::\n\n------------------------------------------------------------------------\n\n### Factors\n\n1.  What is the dependent variable? → [PCB SCORES]{.mohu}\n2.  What is the independent variable of interest? → [HEALTH PROGRAM (4 LEVELS)]{.mohu}\n3.  What is (are) the confounding variables, that the researcher might statistically control for? → [`GENDER`, `STATUS`]{.mohu}\n4.  What is (are) the blocking factors? → [`Schools`, `Classes`]{.mohu}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}