---
title: "`htmltools`: Play with Tachyons"
author: "Jihong Zhang"
date: "2025-03-13"
filters:
  - tachyons
format:
  html:
    page-layout: full
    code-tools: false
    comments: false
    toc-depth: 3
---

## Relevant Resources

-   Official documentation: [Tachyons' component](https://tachyons.io/components/)

## Translate Tachyon to R

### Example 1: [Large Paragraph](https://tachyons.io/components/text/large-paragraph/index.html)

With multiple classes, `class` argument in tags can be a vector.

```{r}
library(htmltools)
```

```{r}
text_paragraph <- "Typography has one plain duty before it and that is to convey information in writing. No argument or consideration can absolve typography from this duty. A printed work which cannot be read becomes a product without purpose."
large_paragraph <- withTags(
  text_paragraph |> 
    p(class = c("f4", "lh-copy measure")) |> 
    main(class = c("pa3", "pa5-ns"))
)
large_paragraph
```

```{r}
str(large_paragraph)
```

### Example 2: Title and Subtitle

```{r}
withTags(
  header(
    h1("This is the title", class = c("f3", "f2-m", "f1-l", "fw2", "black-90", "mv3")),
    h2("This is the subtitle where additional information can go", 
       class = c("f5", "f4-m", "f3-l", "fw2", "black-50", "mt0", "lh-copy"))
  )
)
```

### Example 3: [Logo Title](https://tachyons.io/components/nav/logo-titles-links-centered/index.html)

```{r}
title = "Jihong Zhang"
subtitle = "Play Harder, Learn Harder"
header_class <- "bg-white black-80 tc pv4 avenir"
a_class <- "bg-black-80 ba b--black dib pa3 w2 h2 br-100"
h1_class <- "mt2 mb0 baskerville i fw1 f1"
h2_class <- "mt2 mb0 f6 fw4 ttu tracked"
svg_one_dot <- a(tags$svg(class = "white", `data-icon`="skull", viewBox="0 0 32 32", style="fill:currentcolor"), class = a_class)

tags$header(class = header_class) |> 
    tagAppendChild(svg_one_dot) |> 
    tagAppendChild(h1(title, class = h1_class)) |> 
    tagAppendChild(h2(subtitle, class= h2_class)) 
```
