---
title: "阎罗大王"
author: 吉鸿
date: '2018-09-23'
categories:
  - 闲谈
---

昨儿看了一部韩国电影《与神同行2》。电影主题是赎罪和父爱。但是看的过程我很出戏，因为里面的服饰有古有今。有一感觉有意思的设定就是八大地狱和阎罗王。 https://a.ksd-i.com/a/2018-05-05/105214-609959.jpg

## 阴间

古代人对阴间的刻画是细致入微。阴间是生人死后去的场所。根据我接触过的影视小说，对人死后的世界的描述是生人死后变成魂灵，起初并不知道自己死了。懵懵懂懂过了七天以后，开始逐渐清醒。清醒后，生前的怨气和不甘也涌了出来。黑白无常（阴间使者）会来阳间将死去的魂拘回阴间，在阎罗和判官面前审判。判官对照生死簿，念出死魂的生前阳寿，功过是非。阎王就此质问魂魄，若有罪，被判下十八层地狱服刑，服刑后还要进畜生道受轮回之苦；若无罪，则喝下孟婆汤遗忘前尘往事，立即轮回；若有善行，则轮回进人道或天道。

这么详细的设定，一定不是古人毫无根据杜撰的。这里面混杂着朴素化的古代的司法体系以及宗教伦理观。其中现实投影的部分具有一定的现实讽刺功能。比方说现实中衙门里有冤假错案，阴间自然也有还不少。比如人遭横死，古人会认为是老天爷要让那人做天官或者生死簿上写错了。之前日本很多的漫画《死亡笔记》会不会也借鉴了“生死簿”的设定呢？

## 生死簿

Wiki上说生死簿是记录每个人的寿命长短的册子。若人阳寿未尽，因天灾人祸枉死，且并非大善大恶大冤之人就在枉死城等待阳寿了结。关于枉死城还有很有意思的设定：由于死者在枉死城（特别是自杀的人）受尽孤寂，在世之亲人会请僧侣道士施行“破城”来救魂灵出枉死城。

生前人世间的恩恩怨怨，没想到到了枉死城还是要借助人情才能升天。生死簿是古人“生死有命，富贵在天”的宿命论具现化。好人长命，坏人偿命，冤死之人索命。人世种种皆有业报。中华民族崇敬“死”的文化来自佛教-人死为大。死后的一切都受生前的影响，所以生前当行善才能有果报。

但是生前之事种种真的在死后能一笔勾销么。

## 孟婆汤 & 忘川河

[忘川河](https://baike.baidu.com/item/忘川河/80241)据说是黄泉路和冥界的分界河，类似于古代的护城河。过了就来到了阴间。河上有一座奈何桥，桥边有一位婆婆叫孟婆，喝过孟婆汤走过奈何桥，就忘了前世所有事情。也有说法是，不喝孟婆汤，可以跳入忘川河，等千年再投胎。

人为什么要忘前世种种。是因为人世太苦了，忘记是一种解脱。还是要入轮回的人，只有毫无牵绊才愿意受苦。这样看的话，轮回又是苦的，因为没了经验教训，痴情的人还是痴情下一辈子，命苦的人还是命苦。但是很多人还是愿意相信人可以忘记种种的吧，因为人世实在太苦了。

孟婆应该看到过很多痛苦之人喝汤之后表情不再痛苦。看来，人最终还是很难释怀，只有靠所谓的孟婆汤强行忘记了。
