{
  "hash": "b7bb61379d71e88d28ec4f44f8f136f9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 09: Path Analysis\"\nsubtitle: \"Homework 2\"\nauthor: \"Jihong Zhang*, Ph.D\"\ninstitute: | \n  Educational Statistics and Research Methods (ESRM) Program*\n  \n  University of Arkansas\ndate: \"2024-10-09\"\ndate-modified: \"2024-10-11\"\nsidebar: false\nexecute: \n  echo: true\n  warning: false\noutput-location: default\ncode-annotations: below\nhighlight-style: \"nord\"\nformat: \n  html: \n    page-layout: full\n    toc: true\n    toc-depth: 2\n    toc-expand: true\n    lightbox: true\n    code-fold: false\n    fig-align: center\n---\n\n\n\n# Homework 2\n\n\n\n::: {.cell output-location='default'}\n\n```{.r .cell-code}\nlibrary(ESRM64503)\nlibrary(kableExtra)\nlibrary(tidyverse)\nlibrary(DescTools) # Desc() allows you to quick screen data\nlibrary(lavaan) # Desc() allows you to quick screen data\n# options(digits = 3)\nhead(dataMath)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id hsl cc use msc mas mse perf female\n1  1  NA  9  44  55  39  NA   14      1\n2  2   3  2  77  70  42  71   12      0\n3  3  NA 12  64  52  31  NA   NA      1\n4  4   6 20  71  65  39  84   19      0\n5  5   2 15  48  19   2  60   12      0\n6  6  NA 15  61  62  42  87   18      0\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(dataMath)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 350   9\n```\n\n\n:::\n:::\n\n\n\n## Homework 2: Setup\n\n![Model 1: Diagram of correlation model with perf, use, and mas](hw2_diagram01.png){fig-align=\"center\"}\n\nYou can check the detailed rules of path analysis diagram [here](https://websem.psychstat.org/wiki/_media/manual/websem-draw-pathdiagrams.pdf). Some basic rules:\n\n1.  Observed variables: rectangle/square\n2.  Latent variables: ellipse/circle\n3.  Intercept: triangle shape\n4.  Regression relation: single-headed arrow\n5.  Correlation/Covariance: double-headed arrow\n    1.  Point to itself: residual variance\n    2.  Point to others: covariances\n\n## Homework 2: Model 1 - Correlation Model with perf, use, and mas\n\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nmodel04.syntax = \"\n# Variances:\nperf ~~ perf \nuse ~~ use   \nmas ~~ mas\n\n# Covariance:\nperf ~~ use\nperf ~~ mas\nuse ~~ mas\n\n# Means:\nperf ~ 1  \nuse ~ 1   \nmas ~ 1   \n\"\n\n## Estimation for model01\nmodel04.fit <- cfa(model04.syntax, data=dataMath, mimic=\"MPLUS\", fixed.x = TRUE, estimator = \"MLR\") \n\n## Print output\nstandardizedsolution(model04.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   lhs op  rhs est.std    se      z pvalue ci.lower ci.upper\n1 perf ~~ perf   1.000 0.000     NA     NA    1.000    1.000\n2  use ~~  use   1.000 0.000     NA     NA    1.000    1.000\n3  mas ~~  mas   1.000 0.000     NA     NA    1.000    1.000\n4 perf ~~  use   0.158 0.059  2.685  0.007    0.043    0.273\n5 perf ~~  mas   0.526 0.043 12.372  0.000    0.443    0.610\n6  use ~~  mas   0.299 0.049  6.109  0.000    0.203    0.395\n7 perf ~1        4.719 0.204 23.106  0.000    4.319    5.119\n8  use ~1        3.330 0.143 23.257  0.000    3.050    3.611\n9  mas ~1        2.797 0.126 22.151  0.000    2.550    3.044\n```\n\n\n:::\n\n```{.r .cell-code}\n## filter correlations among varaibles\nstandardizedsolution(model04.fit) |> filter(op == \"~~\", lhs != rhs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   lhs op rhs est.std    se      z pvalue ci.lower ci.upper\n1 perf ~~ use   0.158 0.059  2.685  0.007    0.043    0.273\n2 perf ~~ mas   0.526 0.043 12.372  0.000    0.443    0.610\n3  use ~~ mas   0.299 0.049  6.109  0.000    0.203    0.395\n```\n\n\n:::\n:::\n\n\n\n-   For Performance and Usefulness, there is a weak but significantly positive correlation with **r = .158 (.059), p = .007**\n\n-   For Performance and Anxiety, there is a strong and significantly positive correlation with **r = .526 (.043), p \\< .001**\n\n-   For Usefulness and Anxiety, there is a moderate and significantly positive correlation with **r = .299 (.049), p \\< .001**\n\n## Homework 2: Model 2 - constraining the correlation of use and mas to 0\n\n![Model 2: Constrained model](hw2_diagram02.png){fig-align=\"center\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel04b.syntax = \"\n# Variances:\nperf ~~ perf \nuse ~~ use   \nmas ~~ mas\n\n# Covariance:\nperf ~~ use\nperf ~~ mas\nuse ~~ 0*mas\n\n# Means:\nperf ~ 1  \nuse ~ 1   \nmas ~ 1   \n\"\nmodel04b.fit <- cfa(model04b.syntax, data=dataMath, mimic=\"MPLUS\", fixed.x = TRUE, estimator = \"MLR\") \n\n## Print output\nstandardizedsolution(model04b.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   lhs op  rhs est.std    se      z pvalue ci.lower ci.upper\n1 perf ~~ perf   1.000 0.000     NA     NA    1.000    1.000\n2  use ~~  use   1.000 0.000     NA     NA    1.000    1.000\n3  mas ~~  mas   1.000 0.000     NA     NA    1.000    1.000\n4 perf ~~  use   0.017 0.056  0.298  0.765   -0.092    0.126\n5 perf ~~  mas   0.523 0.044 11.790  0.000    0.436    0.610\n6  use ~~  mas   0.000 0.000     NA     NA    0.000    0.000\n7 perf ~1        4.730 0.206 22.993  0.000    4.327    5.134\n8  use ~1        3.325 0.143 23.212  0.000    3.044    3.606\n9  mas ~1        2.790 0.127 22.056  0.000    2.542    3.038\n```\n\n\n:::\n\n```{.r .cell-code}\nstandardizedsolution(model04b.fit) |> filter(op == \"~~\", lhs != rhs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   lhs op rhs est.std    se      z pvalue ci.lower ci.upper\n1 perf ~~ use   0.017 0.056  0.298  0.765   -0.092    0.126\n2 perf ~~ mas   0.523 0.044 11.790  0.000    0.436    0.610\n3  use ~~ mas   0.000 0.000     NA     NA    0.000    0.000\n```\n\n\n:::\n:::\n\n\n\n-   For Performance and Usefulness, there is a weak and non-significantly positive correlation with **r = .017 (.056), p = .765**\n\n-   For Performance and Anxiety, there is a strong and significantly positive correlation with **r = .523 (.044), p \\< .001**\n\n-   For Usefulness and Anxiety, there is a zero correlation with **r = 0 (0), p = NA**\n\n## Homework 2: AIC and BIC\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(model04.fit, model04b.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nScaled Chi-Squared Difference Test (method = \"satorra.bentler.2001\")\n\nlavaan->lavTestLRT():  \n   lavaan NOTE: The \"Chisq\" column contains standard test statistics, not the \n   robust test that should be reported per model. A robust difference test is \n   a function of two standard (not robust) statistics.\n             Df    AIC    BIC  Chisq Chisq diff Df diff Pr(>Chisq)    \nmodel04.fit   0 6421.3 6456.0  0.000                                  \nmodel04b.fit  1 6446.5 6477.4 27.234     29.031       1  7.123e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n-   For Model 1, AIC = 6421.3 and BIC = 6456.0\n\n-   For Model 2, AIC = 6446.5 and BIC = 6477.4\n\n-   According to the criteria of lower AIC/BIC values indicating better model fit and the result of Likelihood ratio test ($\\chi^2(0, 1)=29.031, p < .001$), we prefer model 1 as it has significantly better model fit than model 2.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}