---
title: "使用R网页抓取：凡人修仙传剧集"
author: "学徒"
date: "2025-03-22"
draft: false
categories: 
  - R语言
  - rvest
execute: 
  warning: false
  message: false
format: 
  html:
    code-tools: false
    code-fold: true
---


## 剧集汇总

从豆瓣网抓取凡人修仙传的简介和每一季的集数。先找到第一到第六以及特别篇的豆瓣网址。

```{r}
#| code-summary: "加载rvest以及stringr包"
library(rvest)
library(stringr)
```

```{r scrap, cache=TRUE}
#| code-summary: "豆瓣网剧集网址"
# 第一季《凡人修仙传：风起天南》
douban_url <- "https://movie.douban.com/subject/"
url_s1 = "34925294/" # 第一季《凡人修仙传：风起天南》
url_s1_2 = "35259437/" # 特别篇《燕家堡之战》          
url_s2 = "35640039/" # 第二季《凡人修仙传：魔道争锋》
url_s3 = "35882624/" # 第三季《凡人修仙传：再别天南》
url_s4 = "36017435/" # 第四季《凡人修仙传：初入星海》
url_s5 = "36139980/" # 第五季《凡人修仙传：星海飞驰》
url_s6 = "36923479/" # 第六季《凡人修仙传：外海风云》
url_all <- c(url_s1, url_s1_2, url_s2, url_s3, url_s4, url_s5, url_s6)

read_html_fanren <- function(douban_url = "https://movie.douban.com/subject/",
                             url) {
  html <- read_html(paste0(douban_url, url))
  return(html)
}


## 简介
get_info <- function(html) {
  html_info <- html_elements(html, css = "div.article > div.related-info")
  info <- html_info |>  
    html_text2() |> 
    str_replace_all("\n", "") |> 
    str_replace_all(" ", "")
  return(info)
}
## 集数
get_ep <- function(html) {
  html_ep <- html_elements(html, css = "div.article > div.episode_list")
  remove_na <- \(x) {x[x != ""]} 
  ep <- html_ep |> 
    html_text2() |> 
    str_split("集", simplify = FALSE) |> 
    unlist() |> 
    remove_na() |> 
    as.numeric()
  return(ep)
}


all_ep <- list(NA)
length(all_ep) <- length(url_all)
all_info <- rep(NA, length(url_all))
for (i in seq(url_all)) {
  html <- read_html_fanren(url = url_all[i]) 
  all_ep[[i]] =  get_ep(html)
  all_info[i] =  get_info(html)
}
```

```{r}
#| code-summary: "分季剧集整理"
cumulative_ep <- all_ep
for (i in 1:length(all_ep)) {
  if (i == 1) {
    cumulative_ep[[i]] = as.numeric(all_ep[[i]])
  }else{
    cumulative_ep[[i]] = as.numeric(all_ep[[i]]) + max(as.numeric(cumulative_ep[[i-1]]))
  }
}
cumulative_ep_col <- sapply(cumulative_ep, \(x) paste0(min(x), "-", max(x)))

## 每一季的起始和结束集数
season_start_end_ep <- data.frame(
  season = seq_along(cumulative_ep),
  ep_start = sapply(cumulative_ep, min),
  ep_end = sapply(cumulative_ep, max)
)
```

```{r}
#| code-summary: "分季剧集汇总"
library(tidyverse)
fanren <- tbl <- tribble(
  ~系列, ~首播,
"第一季《凡人修仙传：风起天南》", "2020-07-25",
"特别篇《凡人修仙传: 燕家堡之战》", "2021-01-31",
"第二季《凡人修仙传：魔道争锋》", "2021-11-14",
"第三季《凡人修仙传：再别天南》", "2022-04-24",
"第四季《凡人修仙传：初入星海》", "2022-07-31",
"第五季《凡人修仙传：星海飞驰》", "2023-07-30",
"第六季《凡人修仙传：外海风云》", "2025-01-18"
)
fanren$`剧集` <- cumulative_ep_col
kableExtra::kable(fanren)
```

```{r}
#| code-summary: "白马侯子的解析视频标题抓取"
library(tidyverse)
## 白马侯子的解析视频
baima_html <- read_html("https://www.bilibili.com/video/BV1jPX4Y6Euz")
baima_titles <- html_elements(baima_html, css = "div.simple-base-item > div.title > div.title-txt") |> 
  html_text2() 

ep_num <- as.numeric(str_replace(str_extract(baima_titles, "\\d+集"), "集", ""))
ep_num <- ifelse(ep_num > 200, NA, ep_num)
ep_num_title <- ifelse(is.na(ep_num), "综合点评", paste0("第", ep_num, "集简介"))

baima_ep_info <- baima_titles |> 
  str_replace_all("解析|解读|逐帧", "") |> 
  str_replace_all("《", "") |> 
  str_replace_all("》", "") |> 
  str_replace_all("【", "") |> 
  str_replace_all("】", "") |> 
  str_replace_all("凡人修仙传", "") |> 
  str_replace_all("第", "") |> 
  str_replace_all("\\d+集", "") |> 
  str_replace_all("\\d+-", "") |> 
  str_replace_all("\\d+/", "") |> 
  str_replace_all("\\d+$", "") |> 
  str_replace_all("（）", "") |> 
  str_replace_all("\\+", "") |> 
  str_replace_all("逻辑梳理", "") |> 
  str_replace_all(" ", "")



```

```{r}
#| code-summary: "利维坦视频抓取"
lwt_html1 <- read_html("https://www.bilibili.com/video/BV1wS4y1X7xb")
lwt_html2 <- read_html("https://www.bilibili.com/video/BV1xeXHYyERT")
lwt_titles <- sapply(list(lwt_html1, lwt_html2), \(x)
                      html_elements(x, css = "div.simple-base-item > div.title > div.title-txt") |> 
                        html_text2(), simplify = TRUE) 
lwt_titles <- unlist(lwt_titles)

## 抓取剧集
lwt_ep_num <- as.numeric(str_replace(str_extract(lwt_titles, "\\d+集|\\d+逐"), "集|逐", ""))
lwt_ep_num_title <- ifelse(is.na(ep_num), "综合点评", paste0("第", ep_num, "集简介"))

## 利维坦视频简介清理
lwt_ep_info <- lwt_titles |> 
  str_replace_all("解析|解读|逐帧", "") |> 
  str_replace_all("《", "") |> 
  str_replace_all("》", "") |> 
  str_replace_all("【", "") |> 
  str_replace_all("】", "") |> 
  str_replace_all("凡人修仙传", "") |> 
  str_replace_all("第", "") |> 
  str_replace_all("\\d+集", "") |> 
  str_replace_all("\\d+-", "") |> 
  str_replace_all("\\d+/", "") |> 
  str_replace_all("\\d+$", "") |> 
  str_replace_all("（）", "") |> 
  str_replace_all("\\+", "") |> 
  str_replace_all("逻辑梳理", "") |> 
  str_replace_all(" ", "")
```

```{r}
#| code-summary: "利维坦视频整理"
get_season <- function(x) {
  ifelse(is.na(x), x,
       season_start_end_ep$season[(x >= season_start_end_ep$ep_start) & (x <= season_start_end_ep$ep_end)])
}

## 将白马侯子的视频简介按季整理成数据框
season_info_all <- data.frame(
  lwt_ep_num,
  lwt_ep_info = lwt_ep_info ## 利维坦
) |> 
  full_join(
    data.frame(
      ep_num,
      ep_info = baima_ep_info), # 白马侯子
    by = c("lwt_ep_num" = "ep_num")
  ) |> 
  mutate(ep_info_all = paste(lwt_ep_info, ep_info)) |>
  mutate(ep_info_all = ifelse(is.na(lwt_ep_num), "综合点评", paste0("第**", lwt_ep_num, "**集简介:", ep_info_all)) ) |>
  rowwise() |>
  mutate(
    season_num = get_season(lwt_ep_num)
  ) |> 
  ungroup() |> 
  mutate(season_num = factor(season_num, levels = 1:length(url_all))) |>
  complete(season_num) |> #填充空白的季
  filter(!is.na(season_num)) |> 
  group_by( season_num) |>
  summarise(ep_info_all = paste0("-  ", ep_info_all, collapse = "\n\n")) |> 
  mutate(ep_info_all = ifelse(ep_info_all == "-  NA", "", ep_info_all) ) |> 
  mutate(ep_info_all = str_replace_all(ep_info_all, "NA", "") )
```

## 分集简介

每集简介是抓取利维坦和白马侯子的视频标题整理而成。

::: macwindow
```{r}
#| results: asis

n_ep_per_s <- sapply(cumulative_ep, length)
show_info_fanren <- glue::glue("### {fanren$系列}（共{n_ep_per_s}集）\n\n 
                               **首播：{fanren$`首播`}** \n\n
                               **剧集：{fanren$`剧集`}** \n\n
                               {all_info}  \n\n
                               {season_info_all$ep_info_all} \n\n"
                               )

show_info_fanren

```
:::

## 其他资源

1.  My previous Bilibili Danmu extraction project ([Github](https://github.com/JihongZ/Danmu_Cloud_mobile/blob/master/bilibili_api.R))
2.  Previous Blog: [Web Scraping Academia Institute's Grant Fundings using R](https://jihongzhang.org/posts/2022/2022-05-12-web-scrapping-grant-fundings-in-r/index.html)
